### ISSUE TITLE
Poor disk performance (tested using diskspd)

### ISSUE THREAD

**Issue by datacore-skumar** [openzfsonwindows/openzfs#10]
zpool command : zpool create -o ashift=12 tank PHYSICALDRIVE1
zvol command : zfs create -o dedup=on -o compression=lz4 -o volblocksize=128k -o sync=always -V 45g tank/vol
![Screenshot (361)](https://user-images.githubusercontent.com/75466339/109611959-0cac7f00-7b55-11eb-92b0-2e93c54b9ccc.png)
![Screenshot (362)](https://user-images.githubusercontent.com/75466339/109611975-11713300-7b55-11eb-93e5-bc436cb69245.png)
![Screenshot (363)](https://user-images.githubusercontent.com/75466339/109611993-159d5080-7b55-11eb-984a-f7d120b84768.png)

**Comment by mailinglists35** [comment]
these two can drastically reduce performance:

-o dedup=on 
-o sync=always

on the same system running linux, do you get the same results?

**Comment by Tsaukpaetra** [comment]
Yeah dedup and force-sync aren't a good idea unless you really need them and know exactly why you need them. The cost of dedup is almost never worth it unless you're literally storing gobs of duplicate data for some reason...
