### ISSUE TITLE
ZFS get all command returns nothing

### ISSUE THREAD

**Issue by datacore-skumar** [openzfsonwindows/openzfs#11]
//zpool creation
C:\Users\WDKRemoteUser\Desktop\install\x64-Release\bin>zpool create -o ashift=12 tank PHYSICALDRIVE1 PHYSICALDRIVE2 PHYSICALDRIVE3

//zvol creation
C:\Users\WDKRemoteUser\Desktop\install\x64-Release\bin>zfs create -o dedup=on -o compression=lz4 -o volblocksize=128k -o sync=always -s -V 200g tank/vol

//ZFS get all returns nothing after zpool and zvol creation
C:\Users\WDKRemoteUser\Desktop\install\x64-Release\bin>zfs get all tank
C:\Users\WDKRemoteUser\Desktop\install\x64-Release\bin>zfs get all tank/vol

**Comment by lundman** [comment]
bd8d764
