### ISSUE TITLE
DV reports mem leak in sysctl_os_registry_change()

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#124]
During ZFS uninstall, DV reports memory leak. Seems like sysctl_os_registry_change() is fired after ZwClose(registry_notify_fd)
 and var 'sysctl_os_RegistryPath' is not freed.

3: kd> !analyze -v

DRIVER_VERIFIER_DETECTED_VIOLATION (c4)
A device driver attempting to corrupt the system has been caught.  This is
because the driver was specified in the registry as being suspect (by the
administrator) and the kernel has enabled substantial checking of this driver.
If the driver attempts to corrupt the system, bugchecks 0xC4, 0xC1 and 0xA will
be among the most commonly seen crashes.
Arguments:
Arg1: 0000000000000062, A driver has forgotten to free its pool allocations prior to unloading.
Arg2: ffffbd87197a0c88, name of the driver having the issue.
Arg3: ffffbd8719c63510, verifier internal structure with driver information.
Arg4: 0000000000000001, total # of (paged+nonpaged) allocations that weren't freed.
	Type !verifier 3 drivername.sys for info on the allocations
	that were leaked that caused the bugcheck.

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 3

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on RM-LT1

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 3

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 78

    Key  : Analysis.System
    Value: CreateObject

BUGCHECK_CODE:  c4

BUGCHECK_P1: 62

BUGCHECK_P2: ffffbd87197a0c88

BUGCHECK_P3: ffffbd8719c63510

BUGCHECK_P4: 1

IMAGE_NAME:  OpenZFS.sys

MODULE_NAME: OpenZFS

FAULTING_MODULE: fffff8066d6e0000 OpenZFS

VERIFIER_DRIVER_ENTRY: dt nt!_MI_VERIFIER_DRIVER_ENTRY ffffbd8719c63510
Symbol nt!_MI_VERIFIER_DRIVER_ENTRY not found.

PROCESS_NAME:  System

STACK_TEXT:  
ffffcd8f`396ecbd8 fffff806`67f37dd2 : 00000000`00000062 00000000`00000003 ffffcd8f`396ecd40 fffff806`67e02640 : nt!DbgBreakPointWithStatus
ffffcd8f`396ecbe0 fffff806`67f37557 : 00000000`00000003 ffffcd8f`396ecd40 fffff806`67e6f0e0 00000000`000000c4 : nt!KiBugCheckDebugBreak+0x12
ffffcd8f`396ecc40 fffff806`67e5b147 : ffffbd87`1763f550 fffff806`67ddc3d3 00000000`0000000d fffff806`00000000 : nt!KeBugCheck2+0x957
ffffcd8f`396ed360 fffff806`685d7e63 : 00000000`000000c4 00000000`00000062 ffffbd87`197a0c88 ffffbd87`19c63510 : nt!KeBugCheckEx+0x107
ffffcd8f`396ed3a0 fffff806`685dff7e : ffffbd87`19c63510 ffffcd8f`396ed490 ffffbd87`197a08a0 ffffbd87`19cc0b40 : nt!VerifierBugCheckIfAppropriate+0xdf
ffffcd8f`396ed3e0 fffff806`67ee5ba6 : ffffbd87`19c63510 00000000`0000024c 00000000`00000001 fffff806`6d6e1000 : nt!VfPoolCheckForLeaks+0x46
ffffcd8f`396ed420 fffff806`685c941a : 00000000`015aa000 ffffbd87`197a08a0 fffff806`680b5570 fffff806`680b5570 : nt!VfTargetDriversRemove+0xd77f6
ffffcd8f`396ed4a0 fffff806`68296850 : ffffbd87`197a08a0 ffffcd8f`396ed5d0 00000000`ffffffff 00000000`00000001 : nt!VfDriverUnloadImage+0x3e
ffffcd8f`396ed4d0 fffff806`683a0ff0 : 00000000`0000000c ffffbd87`ffffffff ffffc003`00000001 ffffcf7c`0336b700 : nt!MiUnloadSystemImage+0x3ac
ffffcd8f`396ed6f0 fffff806`683a0f30 : 00000000`00000000 00000000`00000000 00000000`0000067d ffffbd87`76697244 : nt!MmUnloadSystemImage+0x20
ffffcd8f`396ed720 fffff806`682a6520 : ffffbd87`19c2fca0 00000000`00000000 00000000`00000000 fffff806`680dcd20 : nt!IopDeleteDriver+0x40
ffffcd8f`396ed770 fffff806`67d78634 : 00000000`00000000 00000000`00000000 00000000`00000000 ffffbd87`19c2fcd0 : nt!ObpRemoveObjectRoutine+0x80
ffffcd8f`396ed7d0 fffff806`6835dbdb : ffffbd87`19c70050 00000000`00000000 ffffcd8f`396ed8a8 6c954ebe`f62debfe : nt!ObfDereferenceObject+0xa4
ffffcd8f`396ed810 fffff806`682a6520 : ffffbd87`1910ed70 ffffe405`75f9baa0 6fb04c48`67e911d5 6c954ebe`f62debfe : nt!IopDeleteDevice+0x4b
ffffcd8f`396ed840 fffff806`67d7c009 : 00000000`00000000 00000000`00000000 00000000`00000000 ffffbd87`19c70050 : nt!ObpRemoveObjectRoutine+0x80
ffffcd8f`396ed8a0 fffff806`67dfda8e : ffffbd87`17699ca0 0000267e`38ca1570 ffffbd87`176a8420 00000000`00000001 : nt!ObfDereferenceObjectWithTag+0xc9
ffffcd8f`396ed8e0 fffff806`683841bf : ffffbd87`17699ca0 cb3a4008`00000015 60008fb0`00000000 ffffe405`3f051397 : nt!PnpRemoveLockedDeviceNode+0x252
ffffcd8f`396ed940 fffff806`68383ed2 : 00000000`00000000 ffffcd8f`396ed9c0 ffffe405`76bfec30 00000000`00000001 : nt!PnpDeleteLockedDeviceNode+0x8b
ffffcd8f`396ed980 fffff806`68385c39 : ffffbd87`1910ed70 00000000`00000002 ffffbd87`1910ed70 00000000`00000000 : nt!PnpDeleteLockedDeviceNodes+0xba
ffffcd8f`396ed9f0 fffff806`683811aa : ffffcd8f`396edb01 ffffbd87`17699c00 fffff806`682f7a00 ffffe405`00000001 : nt!PnpProcessQueryRemoveAndEject+0x4a9
ffffcd8f`396edac0 fffff806`682f7d00 : ffffe405`783508d0 ffffe405`77a21510 ffffe405`77a21510 00000000`00000000 : nt!PnpProcessTargetDeviceEvent+0xea
ffffcd8f`396edaf0 fffff806`67d1bcba : ffffbd87`17746ce0 ffffbd87`3d109040 fffff806`682f7af0 ffffbd87`3d2fa590 : nt!PnpDeviceEventWorker+0x210
ffffcd8f`396edb70 fffff806`67ce4bf5 : ffffbd87`3d109040 ffffbd87`17695340 ffffbd87`3d109040 00007fff`c151d710 : nt!ExpWorkerThread+0x16a
ffffcd8f`396edc10 fffff806`67e624bc : ffff9680`d6cb1180 ffffbd87`3d109040 fffff806`67ce4ba0 ffffe405`76a83200 : nt!PspSystemThreadStartup+0x55
ffffcd8f`396edc60 00000000`00000000 : ffffcd8f`396ee000 ffffcd8f`396e8000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x1c

STACK_COMMAND:  .thread ; .cxr ; kb

FAILURE_BUCKET_ID:  0xc4_62_VRF_LEAKED_POOL_IMAGE_OpenZFS.sys

OS_VERSION:  10.0.17763.1

BUILDLAB_STR:  rs5_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {b354d31d-5495-43c2-4304-981017d30dc9}

Followup:     MachineOwner
---------

3: kd> !verifier 3 openzfs.sys

Verify Flags Level 0x001209bb

  STANDARD FLAGS:
    [X] (0x00000000) Automatic Checks
    [X] (0x00000001) Special pool
    [X] (0x00000002) Force IRQL checking
    [X] (0x00000008) Pool tracking
    [X] (0x00000010) I/O verification
    [X] (0x00000020) Deadlock detection
    [X] (0x00000080) DMA checking
    [X] (0x00000100) Security checks
    [X] (0x00000800) Miscellaneous checks
    [X] (0x00020000) DDI compliance checking

  ADDITIONAL FLAGS:
    [ ] (0x00000004) Randomized low resources simulation
    [ ] (0x00000200) Force pending I/O requests
    [ ] (0x00000400) IRP logging
    [ ] (0x00002000) Invariant MDL checking for stack
    [ ] (0x00004000) Invariant MDL checking for driver
    [ ] (0x00008000) Power framework delay fuzzing
    [ ] (0x00010000) Port/miniport interface checking
    [ ] (0x00040000) Systematic low resources simulation
    [ ] (0x00080000) DDI compliance checking (additional)
    [ ] (0x00200000) NDIS/WIFI verification
    [ ] (0x00800000) Kernel synchronization delay fuzzing
    [ ] (0x01000000) VM switch verification
    [ ] (0x02000000) Code integrity checks

  RESERVED FLAGS (use of these flags is unsupported):
    [X] (0x00100000) Unused or reserved flag

    [X] Indicates flag is enabled

Summary of All Verifier Statistics

  RaiseIrqls           0x0
  AcquireSpinLocks     0x2
  Synch Executions     0x0
  Trims                0x0

  Pool Allocations Attempted             0x49012
  Pool Allocations Succeeded             0x49012
  Pool Allocations Succeeded SpecialPool 0x49012
  Pool Allocations With NO TAG           0x0
  Pool Allocations Failed                0x0

  Current paged pool allocations         0x1 for 00000002 bytes
  Peak paged pool allocations            0x2 for 000000E4 bytes
  Current nonpaged pool allocations      0x0 for 00000000 bytes
  Peak nonpaged pool allocations         0x26 for 20124A50 bytes

Driver Verification List
------------------------

nt!_VF_TARGET_DRIVER 0xffffbd8719cc0b40: openzfs.sys (Loaded)

    Pool Allocation Statistics: ( NonPagedPool / PagedPool )

      Current Pool Allocations: ( 0x00000000 / 0x00000001 )
      Current Pool Bytes:       ( 0x00000000 / 0x00000002 )
      Peak Pool Allocations:    ( 0x00000026 / 0x00000002 )
      Peak Pool Bytes:          ( 0x20124a50 / 0x000000e4 )
      Contiguous Memory Bytes:       0x00000000
      Peak Contiguous Memory Bytes:  0x00000000

    Pool Allocations:

      Address             Length      Tag   Caller Address    
      ------------------  ----------  ----  ------------------
      0xffffe40572818ff0  0x00000002  VStr  0xfffff8066d802698  OpenZFS!sysctl_os_registry_change+0x58

    Contiguous allocations are not displayed with public symbols.

3: kd> dt openzfs!sysctl_os_RegistryPath
 ""   +0x000 Length           : 0
   +0x002 MaximumLength    : 2
   +0x008 Buffer           : 0xffffe405`72818ff0  ""
3: kd> dx -id 0,0,ffffbd8717695340 -r1 ((OpenZFS!wchar_t *)0xffffe40572818ff0)
((OpenZFS!wchar_t *)0xffffe40572818ff0)                 : 0xffffe40572818ff0 : "" [Type: wchar_t *]
3: kd> dt openzfs!registry_notify_fd
(null)

**Comment by lundman** [comment]
The latest commit: https://github.com/openzfsonwindows/openzfs/blob/windows/module/os/windows/zfs/sysctl_os.c#L180
address somethings, any "return" statement here would skip the close() function, i address many of them, I do think there is one more though

**Comment by lundman** [comment]
closed with PR, thx
