### ISSUE TITLE
destroy freshly created pool cause BSOD on windows 10

### ISSUE THREAD

**Issue by Musickiller** [openzfsonwindows/openzfs#162]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 
Distribution Version	| 10
Kernel Version	|
Architecture	| x64
OpenZFS Version	| OpenZFSOnWindows-debug-2.1.99-1005-g5d39a0e3d-dirty (zfs-2.0.0-2)

### Describe the problem you're observing
After a pool is created as in here (https://github.com/openzfsonwindows/openzfs/issues/7#issue-809773848), I've called "destroy" (wanted to change creation parameters), which caused BSOD

### Describe how to reproduce the problem
```
fsutil file createnew D:\poolfile.bin 500000000
zpool create daddy \\?\D:\poolfile.bin
zpool status
destroy daddy
```

### Include any warning/errors/backtraces from the system logs
please tell me where to find logs 👶

last thing I have seen in the console was something like zfsunmount for a briefest of moments

_note for myself: crash happened at about 2022-10-06 17:10_

**Comment by andrewc12** [comment]
Hi, I beleive we've fixed some crashes related to unmounting since that version of the driver, so you might want to use a newer version of the fully signed driver from here https://openzfsonosx.org/wiki/Windows_builds

The newest one actually came out today.

**Comment by Musickiller** [comment]
this one was fast! I confirm this solved =D 🥳👍
