### ISSUE TITLE
Finding the Newest release is difficult

### ISSUE THREAD

**Issue by bcredeur97** [openzfsonwindows/openzfs#182]
Not really a bug or feature request, so was unsure how to put this:

Finding the newest releases (on the nightly builds page here: https://openzfsonosx.org/wiki/Windows_builds ) seems to be harder than it should be, the Github Releases page only has this as the newest build: OpenZFSOnWindows-debug-2.1.99-1005-g5d39a0e3d-dirty.exe which I'm pretty sure is old at this point. 

Just seeing that the project entered Beta, it may be better if that's a bit easier to get to :) Perhaps could a link be added to the primary readme? Or even just being sure to put the newest release on the github releases page? Whatever is easiest for everyone!

**Comment by lundman** [comment]
We are actually building toward another github release, which will be out soon. During the big changes, and debugging, nightlies can be produced more quickly for testing specific problems, so there are releases made just for one specific bug to test., and sometimes working on multiple bugs at the same time. It is definitely fast moving, and it helps if the tester can produce stack dumps if it is wrong.
So github releases is meant to be more stable, for users not interested in the bleeding edge, or higher chance of BSODS, so they do lag behind a bit. But the next release should bring everything level again.
