### ISSUE TITLE
Hard crash on scrub

### ISSUE THREAD

**Issue by polarbub** [openzfsonwindows/openzfs#207]
### System information

Type | Windows 10 Pro, Version 22H2, OS build 19045.2364, Experience Windows Feature Experience Pack 120.2212.4190.0
 --- | ---
Distribution Name	| openzfsonwindows
Distribution Version	| zfswin-2.1.6rc3 zfs-kmod-zfswin-2.1.6rc3
Kernel Version	| 
Architecture	| x86_64
OpenZFS Version	| 

### Describe the problem you're observing
When I run `zfs scrub tank` the system blue screens. I don't see a typical windows blue screen, the system just stops responding and restarts. That might be because I'm using a vm and virtio-vga and that won't render blue screens right. I don't see any error class logs in event viewer, only information level ones in the application tab. See the pastebin link below.

### Describe how to reproduce the problem
```
 fsutil file createnew 1.bin 200000000
 fsutil file createnew 2.bin 200000000
 fsutil file createnew 3.bin 200000000
zpool create -O casesensitivity=insensitive -O atime=off -o ashift=12 tank raidz \\?\C:\Users\polarbub\Documents\zfs\1.bin \\?\C:\Users\polarbub\Documents\zfs\2.bin \\?\C:\Users\polarbub\Documents\zfs\3.bin
zfs set driveletter=Z tank 
zfs set mountpoint=/ tank
zfs scrub tank
```

### Include any warning/errors/backtraces from the system logs
I don't know really where to go for proper logs. Here is what is copied out of event viewer. https://pastebin.com/PzMxgg6X

**Comment by lundman** [comment]
Thanks for reporting this. I had hoped that we fixed what I assume is the stack issue.
Looks like you got a memry.dmp though, you do this https://openzfsonosx.org/wiki/Windows_BSOD to 
get a stack - but it's a bit of a hassle, so I don't blame you if you would rather not

Meanwhile, I'll try what you suggest. I am surprised you didnt copy any data to the pool.

**Comment by lundman** [comment]
oh hey, that died immediately

**Comment by lundman** [comment]
```
 	OpenZFS!spa_strfree+0x13 [C:\src\openzfs\module\zfs\spa_misc.c @ 1489]	C/C++/ASM
>	OpenZFS!vdev_file_open+0x773 [C:\src\openzfs\module\os\windows\zfs\vdev_file.c @ 244]	C/C++/ASM
 	OpenZFS!vdev_open+0x376 [C:\src\openzfs\module\zfs\vdev.c @ 1949]	C/C++/ASM
 	OpenZFS!vdev_open_child+0x32 [C:\src\openzfs\module\zfs\vdev.c @ 1758]	C/C++/ASM
 	OpenZFS!taskq_thread+0x4ff [C:\src\openzfs\module\os\windows\spl\spl-taskq.c @ 2083]	C/C++/ASM

	spa_strfree(vdev_path);

	vdev_path = NULL

```

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/openzfs/commit/eed7d32827dcfd277191f654cd339235a043d2e4

**Comment by polarbub** [comment]
Do you still want me to make a stack trace and dump?

**Comment by lundman** [comment]
Nah, no need. If you get new crashes, maybe.

**Comment by polarbub** [comment]
Did you post binaries or do I need to build myself?
If I need to build myself how to I fix this error? ```SignTool error : No certificates were found that met all the given criteria.``` Full log: https://pastebin.com/hm4Q6dHH

**Comment by lundman** [comment]
Grab the rc4 installer from here:  https://github.com/openzfsonwindows/openzfs/releases/tag/zfswin-2.1.6rc3
(url is rc3 as I've not yet pushed the tags)

You can build yourself, and getting a cert is very difficult - but - you can enable TestMode on your Windows target machine, and load without codesigning.

**Comment by polarbub** [comment]
I'll just use the binaries. Thanks!
