### ISSUE TITLE
a way to limit arc size

### ISSUE THREAD

**Issue by clarity99** [openzfsonwindows/openzfs#208]
### Describe the feature would like to see added to OpenZFS

I'd like a way to be able to limit arc size on Windows. For Linux these options seem to be set from zfs.conf, but I cannot find any documentation on how to do this on Windows.

**Comment by lundman** [comment]
We went Windows-y with the tunables, see https://openzfsonosx.org/wiki/Windows_Registry
So in theory, you can just change 
\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\OpenZFS\zfs_arc_max

**Comment by clarity99** [comment]
I've tried that, but it didn't seem to help. I've also been experiencing so many BSODs, I gave up at the moment and will try when it's more stable.
