### ISSUE TITLE
Can´t rename any file in a dataset

### ISSUE THREAD

**Issue by Gustavo-4523** [openzfsonwindows/openzfs#215]
Hey, i am starting my carrer in IT and i have came across some new things, and some of then are challenging.
I am actualy trying to implement an ZFS dataset in windows server 2019, i have successfully create a pool in raidz2, and it can storage files and is persistent and all, but i can't see to solve the issue with SMB share in new datasets.
![SMB](https://user-images.githubusercontent.com/128062562/228013400-b6d80c9a-90ef-4c00-8ebe-3a10193aae02.png)

Plus, in a dataset, i can't create new files or move old ones there, or create workspaces
![git hub](https://user-images.githubusercontent.com/128062562/228013427-9661cd4f-913b-4d1b-9e02-da741ea60a42.png)
![new folder error](https://user-images.githubusercontent.com/128062562/228013430-4f578585-b447-4e5a-a35d-8649fc7f3309.png)

I know this problaly is a newbie issue and fairly easy to solve, but i dont came across any solution. If im asking this in the wrong section i'm sorry in advance

**Comment by lundman** [comment]
Hello! We have not added SMB sharing helper in ZFS, you can share it by hand using Windows tools. We have just not got to the automatic-sharing part.

The other issues are interesting. Does this happen on the top level dataset, mounted as "H:" ? Only lower datasets? Image looks like H: also fails.

Finally, did you use https://github.com/openzfsonwindows/openzfs/releases/tag/zfswin-2.1.7rc1   ?

**Comment by Gustavo-4523** [comment]
> 
oh, good to know
the other issues, yes, in top level "H:" i can create files/folders and move external files there, but in lower data sets i cant move or create new files/folders

**Comment by Gustavo-4523** [comment]
i get the same error trying to create new files, but when i try move some into the "home" dataset i get permissions error like this:

![permissão](https://user-images.githubusercontent.com/128062562/228266007-249012f5-c53f-4bec-a950-d1141e746a72.png)

such as rename error, this happens

![rename](https://user-images.githubusercontent.com/128062562/228266878-b538a8cd-8b88-4fed-a4c7-d79563110647.png)
![rename pt2](https://user-images.githubusercontent.com/128062562/228266895-8cd926fc-f685-43b0-be29-24361892d5a1.png)
![rename pt3](https://user-images.githubusercontent.com/128062562/228266912-3223565e-549c-4392-afaf-c4eb46ab6512.png)

**Comment by Gustavo-4523** [comment]
the method to create the raidz (with 8 physical disks) was with this command line _"zpool create -O casesensitivity=insensitive -O compression=lz4 -O atime=off -o ashift=12 tank raidz PHYSICALDRIVE4 PHYSICALDRIVE0 PHYSICALDRIVE7 PHYSICALDRIVE3 PHYSICALDRIVE1 PHYSICALDRIVE6 PHYSICALDRIVE2 PHYSICALDRIVE5"_ wich create and external drive all clean, the import and export command work just fine and the files we leave in the pool persists as normal

![image](https://user-images.githubusercontent.com/128062562/228274556-8d08b06e-2d00-422f-a55c-4ca796f1849e.png)

the pool as showed in here works just fine

**Comment by lundman** [comment]
OK thanks, I'll look at replicating that. the "sub volume mounting inside ZFS mount" is completely different for Windows (as its reparse points) so I wouldn't be too surprised if there are issues there. I would guess if you made all datasets have a driveletter it (might) work better. But needs to be fixed either way.

**Comment by Gustavo-4523** [comment]
that maybe work, but how can I mount one or more dataset and assign driveletters to them ?

**Comment by Gustavo-4523** [comment]
I tried some commands and i get this:
the pool is mounted as readonly and i cant change this since i get this error message
![readonly](https://user-images.githubusercontent.com/128062562/228881640-f338dde3-0dab-4887-bf58-e6d76cd0338b.png)
![readonly off](https://user-images.githubusercontent.com/128062562/228879979-e4d8f077-d6c4-43b0-9e95-f891e5b70d97.png)

And about the driveletter, i was able to active this property but i cant assign a specific letter to it, the line works but the letter is completely different than the one i get
![driveletter](https://user-images.githubusercontent.com/128062562/228880249-86888ec1-828d-4317-97c6-6f92b97a6ac2.png)
![driveletter (2)](https://user-images.githubusercontent.com/128062562/228882309-b3d1a3d9-cd7d-4101-818a-c4e59d779421.png)
![letter assign](https://user-images.githubusercontent.com/128062562/228882077-43dc35c8-54e5-4d64-9d44-b9abfa080abc.png)
png)

**Comment by Gustavo-4523** [comment]
this probaly make some difference, but i test it in windows 10 and get the same problem
currently using windows server 2019

**Comment by Gustavo-4523** [comment]
i did this, but nothing change after import. 
about data, its persistent through export/import and reboot in general.
the issue i see is that a cant remove this readonly property to write new files or modify old ones.

**Comment by lundman** [comment]
Neat - I guess I would try

"zpool import -N poolname"
"zfs set readonly=off ....."
"zpool export poolname"
"zpool import poolname"

**Comment by Gustavo-4523** [comment]
I run this commands, but nothing changes unfortunaly :/

![zpool -n](https://user-images.githubusercontent.com/128062562/229192858-090beda5-b733-4b00-a293-689fae8ea34e.png)
![zfs only=off](https://user-images.githubusercontent.com/128062562/229192883-f2049e24-d8f5-4f09-ab37-659b6aec2830.png)
![only off](https://user-images.githubusercontent.com/128062562/229192925-b141c3b3-23ae-4eb6-b6d2-06fa51fe983e.png)

again, exports and imports works just fine

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/openzfs/commit/fdc4c1e18c3f60e5397764a4fed82fd0ea62c31b

Please try rc2
https://github.com/openzfsonwindows/openzfs/releases/tag/zfswin-2.1.7rc1

**Comment by Gustavo-4523** [comment]
Hey, sorry for the long wait, i'm being busy with some stuff in the work and hadn't time to work this out until now. It seens to be working just fine with this updated, tried some files in the main pool and in an dataset and even change one of the files type and it worked fine. Gonna run some more tests and if i found some other issues i'm sure to give you a heads up.

Thank you very much for your help and patience and keep the good work in this projetc for us windows users :D
Cheers.
