### ISSUE TITLE
rc3: Windows Defender scans hang with zpool imported/mounted

### ISSUE THREAD

**Issue by colemickens** [openzfsonwindows/openzfs#224]
### System information

Windows, OpenZFS RC3 release

### Describe the problem you're observing

Windows Defender was unable to finish a Quick Scan.

### Describe how to reproduce the problem

Mount a zpool, try to complete a Windows Defender quick scan.

I had numerous failures over multiple weeks. The second that I exported the pool and rescanned, it finished successfully.

**Comment by lundman** [comment]
I believe this issue has been fixed. If the issue persist, please reopen.
