### ISSUE TITLE
no files in dataset show up from windows

### ISSUE THREAD

**Issue by Xynonners** [openzfsonwindows/openzfs#238]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 11 Enterprise
Distribution Version	| 10.0.22621 Build 22621
Kernel Version	| NT
Architecture	| x86_64
OpenZFS Version	| zfswin-2.1.7rc3-dirty

### Describe the problem you're observing

Files show up inside dataset from linux but all dataset files are "missing" in windows (both explorer and ls from commandline). ZFS properties still shows used size correctly. Files located inside the pool but not inside a dataset still show up correctly.

Unmounting and remounting datasets and pool, along with exporting and importing, does not fix the issue.

I did accidentally run a zpool destroy on linux before but reimported the pool via zpool import -D

### Describe how to reproduce the problem

Always occurs on my system (used to work with 2.1.6 and 21H2, updated to 22H2 and 2.17 and seems to no longer function).

### Include any warning/errors/backtraces from the system logs

I dunno :(

**Comment by lundman** [comment]
Thanks for reporting it, so we suspect there might be an issue with `import -D` ? Can't say I've tried it yet, so that is possible.
Could also be 22H2 is using a different directory listing type, I'll have to see if I can update one of my VMs and see (anyone got 22H2 running?)

**Comment by Xynonners** [comment]
I did the zpool destroy from linux, then reimported via zpool import -D from linux again with no issues (all data still intact).

Both windows and linux on startup still use zpool import (without D flag) during system startup, and export on shutdown.

During remount and reimports no errors are thrown??? However I can only see files from linux rather than windows.

Unless windows is somehow seeing the destroy in the transaction logs and refusing to show files (only in datasets though! files in the base filesystem still show up for some reason), I would be leaning towards it being a 22H2 issue. Just speculating though.

**Comment by lundman** [comment]
What does `zfs mount` say? Are you saying you can see things in the `pool` part, but no lower datasets?

**Comment by Xynonners** [comment]
yup, can see files in pool but no lower datasets

datasets are considered already mounted by zfs mount/unmount.

**Comment by lundman** [comment]
ok so reparse points have a bug then. you can probably set driveletter=G on one of the lower datasets, and re-import and it will be on G:

**Comment by Xynonners** [comment]
Alright, did that and the files showed up as expected.

**Comment by lundman** [comment]
I have grabbed the latest Win11 VM and tested and can not replicate this issue.

Do you think you could make a ~1g pool, file or disk-file, that exhibits this issue and send it to me?

**Comment by sskras** [comment]
@lundman, just in case: (1) what is the full version/build, and (2) is it an Enterprise distribution?

**Comment by lundman** [comment]
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
Windows 11 Enterprise Evaluation
22H2 22621.1848

**Comment by TomsonRiviera** [comment]
> ok so reparse points have a bug then. you can probably set driveletter=G on one of the lower datasets, and re-import and it will be on G:

I have the same problem. Could you please explain how to set the driveletter? Thx.

**Comment by lundman** [comment]
```
zfs set driveletter=G pool/dataset
zpool export pool
zpool import pool
```

any play pool for me to test? or is it a windows issue. Can someone run `FileSpy` on the ZFS volume when listing an "empty" dir?

**Comment by lundman** [comment]
OK I can now reproduce this now. It looks like the mountpoint directory it creates to mount isn't made into a reparse point (whereas when you zfs create on Windows, it automatically is)

**Comment by lundman** [comment]
oh heh nah, it just creates an empty directory for the mount. So when I test a pool on windows, and create entries in the "lower" dataset, it's actually just populating the root.

```
 $ dd if=/dev/random of=/e/lower2/file.bin bs=1M count=200
 209715200 bytes (210 MB, 200 MiB) copied, 81.4204 s, 2.6 MB/s
 $ out/build/x64-Debug/cmd/zfs/zfs list
 NAME             USED  AVAIL  REFER  MOUNTPOINT
 BOOM             370M  18.5G   370M  /BOOM
 BOOM/lower2       24K  18.5G    24K  /BOOM/lower2
```

so that is rather amusing. Working on it..

**Comment by lundman** [comment]
f25ade0

**Comment by lundman** [comment]
I pushed out an rc2 with this fix.

**Comment by lundman** [comment]
I believe this issue has been fixed. If the issue persist, please reopen.
