### ISSUE TITLE
zfs-windows-2.2.0-rc1 release commit is not available in the repository

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#239]
The release links to this commit, but it is not in the repository:

https://github.com/openzfsonwindows/openzfs/commit/b558c6ef2c95d74a8d2ff3d9a5a887028343288c

On the linked page it says

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by lundman** [comment]
Ah looks like I pushed the tag, not the branch.

Hows that?

**Comment by EchterAgo** [comment]
I can fetch the commit now, thanks!
