### ISSUE TITLE
SYSTEM_SERVICE_EXCEPTION BSOD when running kstat

### ISSUE THREAD

**Issue by d-uzlov** [openzfsonwindows/openzfs#241]
### System information

```powershell
PS C:\Windows\system32> zfs version
zfswin-2.2.0rc1
zfs-kmod-zfswin-2.2.0rc1

PS C:\Windows\system32> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0
```

### Describe the problem you're observing

kstat causes immediate BSOD, regardless of parameters.

### Describe how to reproduce the problem

- Run `kstat` without any parameters in an elevated powershell terminal

### Include any warning/errors/backtraces from the system logs

I don't know how to get any specific error info.
I can post it if there is some instruction on how to gather it.

**Comment by lundman** [comment]
Ah thank you for reporting it. kstat is mostly going to be removed, since we now store tunables in registry. Also, it will stay for arcstat, so I will fix it :)

**Comment by lundman** [comment]
```
VERIFY3( IrpSp->Parameters.DeviceIoControl.OutputBufferLength >= sizeof (ksp) ) failed (956 >= 964)
Break instruction exception - code 80000003 (first chance)
OpenZFS!spl_kstat_chain_id+0xb0:

Parameters.DeviceIoControl.OutputBufferLength = 0x3bc
kd> ?? sizeof(ksp)
unsigned int64 0x3c4
```

So the userland and kernel struct mismatch (again!) I wonder if a CTASSERT or similar could be employed here to catch it sooner.

**Comment by lundman** [comment]
OK, confirmed

```

sizeof(kernel_mutex)
40

 ?? sizeof(kmutex_t)
unsigned int64 0x30 = 48


```

**Comment by lundman** [comment]
Nah means the commit dbd33f6a728 should also have included f3eadcb

**Comment by lundman** [comment]
[kstat.zip](https://github.com/openzfsonwindows/openzfs/files/12093539/kstat.zip)

This exe should work until next release.

**Comment by lundman** [comment]
Ah hmm, guess that wont be signed

**Comment by sskras** [comment]
Thanks for the explanation! : )

**Comment by lundman** [comment]
I believe this issue has been fixed. If the issue persist, please reopen.
