### ISSUE TITLE
bugcheck because of DbgBreakPoint() in ExecuteWmiMethod()

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#243]
_SYSTEM_SERVICE_EXCEPTION (3b)
An exception happened while executing a system service routine.
Arguments:
Arg1: 0000000080000003, Exception code that caused the bugcheck
Arg2: fffff803802553a2, Address of the instruction which caused the bugcheck
Arg3: ffff97809fbdee60, Address of the context record for the exception that caused the bugcheck
Arg4: 0000000000000000, zero._

`8: kd> k

00 ffff9780`9fbde578 fffff801`d5df43a9 nt!KeBugCheckEx
01 ffff9780`9fbde580 fffff801`d5df367c nt!KiBugCheckDispatch+0x69
02 ffff9780`9fbde6c0 fffff801`d5dec02d nt!KiSystemServiceHandler+0x7c
03 ffff9780`9fbde700 fffff801`d5d7a2a1 nt!RtlpExecuteHandlerForException+0xd
04 ffff9780`9fbde730 fffff801`d5d790c4 nt!RtlDispatchException+0x421
05 ffff9780`9fbdee30 fffff801`d5df4482 nt!KiDispatchException+0x1e4
06 ffff9780`9fbdf4e0 fffff801`d5dee892 nt!KiExceptionDispatch+0xc2
07 ffff9780`9fbdf6c0 fffff803`802553a3 nt!KiBreakpointTrap+0x2d2
08 ffff9780`9fbdf850 fffff803`803f750f ZFSin!ExecuteWmiMethod+0x223 [C:\BuildAgent\work\9f5ca3432854b81\module\os\windows\zfs\zfs_windows_zvol_wmi.c @ 1040] 
09 ffff9780`9fbdf8b0 fffff803`803f70eb ZFSin!ScsiWmipProcessRequest+0x223 [\drivers\storage\scsiwmi\wmilib.c @ 738] 
0a ffff9780`9fbdf930 fffff803`802555ee ZFSin!ScsiPortWmiDispatchFunction+0x7b [\drivers\storage\scsiwmi\wmilib.c @ 823] 
0b ffff9780`9fbdf9a0 fffff803`80225078 ZFSin!HandleWmiSrb+0x4e [C:\BuildAgent\work\9f5ca3432854b81\module\os\windows\zfs\zfs_windows_zvol_wmi.c @ 201] 
0c ffff9780`9fbdf9f0 fffff803`7c9c5a77 ZFSin!wzvol_HwStartIo+0x1d8 
`
FAULTING_SOURCE_LINE:  C:\BuildAgent\work\9f5ca3432854b81\module\os\windows\zfs\zfs_windows_zvol_wmi.c

FAULTING_SOURCE_LINE_NUMBER:  1040

FAULTING_SOURCE_CODE:  
  1038: 	default:
  1039: 		__try {
> 1040: 			DbgBreakPoint();
  1041: 		}
  1042: 		__except(EXCEPTION_EXECUTE_HANDLER) {
  1043: 		}

**Comment by datacore-rm** [comment]
To repro:-
_$portWWN = "3456789A"
[byte[]]$portWWNArr = $portWWN.ToCharArray()
Get-WMIObject -Class MSFC_HBAAdapterMethods -Namespace root\wmi | ForEach-Object_ {$_.GetFC4Statistics($portWWNArr,8)}


In zfsin(compiled with MSVC), DbgBreakPoint()  is converted into __debugbreak  and it does not bugcheck.

#if (_MSC_FULL_VER >= 150030729) && !defined(IMPORT_NATIVE_DBG_BREAK)
  #define DbgBreakPoint __debugbreak
#else
__analysis_noreturn
VOID
NTAPI
DbgBreakPoint(
    VOID
    );

But with openzfs/clang, it is compiled to DbgBreakPoint() function which bugchecks.

Can we remove this DbgBreakPoint() line as it is not useful here? Shall I create a PR with this change?

**Comment by lundman** [comment]
I believe those lines are unmodified from the storport examples. We should remove them to survive unknown requests and maybe check what the requests are in case we should support them..

**Comment by datacore-rm** [comment]
Thanks. Would you like me to create a PR removing those lines?

**Comment by lundman** [comment]
I dont mind, if you feel keen you can, or I'll do it next build :)
