### ISSUE TITLE
In zdb.exe,  most commands abort() with ASSERTion failing

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#25]
Export a zpool  and run the command "zdb.exe -e poolname"

File: spa_misc.c 
Function: spa_lookup()
Line: ASSERT(MUTEX_HELD(&spa_namespace_lock));

This lock was already held by the thread in the calling function spa_import() (spa.c)

Analysis:-
The file "lib/os/windows/libpthread/pthread.h" has been changed as part of commit https://github.com/openzfsonwindows/openzfs/commit/e594838dbc8415425f76c40324df4edef56977cc.

The pthread global variables have been made static and hence the files(spa.c & spa_misc.c) are getting separate instance of each variable.

**Comment by lundman** [comment]
yep, just rolling that back now - it was a misleading error due to other variables being duplicate

**Comment by datacore-rm** [comment]
I also quickly tested the changes and am not seeing the issue now. Thanks for the quick turnaround.
