### ISSUE TITLE
FileRenameInformation does not work with long file names

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#257]
When trying to rename a path longer than `MAXNAMELEN` (256) bytes the `set_file_rename_information` function fails with `STATUS_ILLEGAL_CHARACTER`. This is the issue mentioned in #255

**Comment by EchterAgo** [comment]
rclone initially creates the file with a `.partial` suffix and when done copying is renaming the file. The first step succeeds, despite `FASTIO_WRITE` errors, but then the rename fails and rclone does not like that.

**Comment by EchterAgo** [comment]
To reproduce:

```
$Path = "\\?\D:\directory\directo\directorydirectorydirectorydire2"
$Name = "file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file filefffffffffff file file"

Write-Host "Deleting $Path"
Remove-Item -Recurse -Force $Path

Write-Host "Creating $Path"
$DirItem = New-Item -Path $Path -ItemType Directory

Write-Host "Creating $Name ($($Path.Length + $Name.Length) chars)"
$FileItem = New-Item -Path $Path -Name $Name -ItemType File -Value "contents contents contents"

#$FileItem | Format-List

Write-Host "Renaming $Name"
Rename-Item $FileItem -NewName "$Name.test"

Write-Host "Removing $Name"
Remove-Item $FileItem

# File still exists
Write-Host "Listing files in $Path"
Get-ChildItem "$Path" -Recurse
```

**Comment by lundman** [comment]
`FASTIO_WRITE` aren't error, fastio is optional, so it returns error, and Windows kernel will fall back to proper IRP call. I did commit FASTIO support earlier in the week though.

I'm curious about the name.partial. Since we do convert the name from UTF16 to UTF8, and if there isn't enough room it returns STATUS_ILLEGAL_CHARACTER - but is it sending longer filenames than what is allowed somehow? Or do we have the wrong max-filename in rename? I fixed it recently too.

Thanks for the reproducer

**Comment by EchterAgo** [comment]
I think we have the wrong max length. Windows paths can be up to 32K when prefixed with `\\?\`

**Comment by lundman** [comment]
ho boy - that's not going to fly. We should at least return a better error

**Comment by EchterAgo** [comment]
We already allow creation of files with long names.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#:~:text=The%20maximum%20path%20of%2032%2C767%20characters%20is%20approximate

**Comment by lundman** [comment]
ok sounds like 260 for each component, with a maximum of 32767 (65536/WCHAR).
So we should at least 256->260 in rename

**Comment by lundman** [comment]
and then handle zfs_rename returning ETOOWHATEVERITIS and return the correct STATUS_

**Comment by EchterAgo** [comment]
There seems to also be a potential overflow in there. I just had a stack
overrun when trying the test with a filename of 250 chars (have to check
this again when the system restarts)

**Comment by EchterAgo** [comment]
```powershell
$Path = "\\?\D:\directory\directo\directorydirectorydirectorydire2"
$Name = "file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file file fil"

Write-Host "Creating $Path"
$DirItem = New-Item -Path $Path -ItemType Directory

Write-Host "Creating $Name ($($Path.Length + $Name.Length) chars, dir = $($Path.Length), file = $($Name.Length))"
$FileItem = New-Item -Path $Path -Name $Name -ItemType File -Value "contents contents contents"
```

seems to happen when the path total is exactly 250 characters.

**Comment by EchterAgo** [comment]
I think `buffer[outlen] = 0;` overwrites a byte after the buffer.

**Comment by EchterAgo** [comment]
There are multiple of these `RtlUnicodeToUTF8N` calls that will overflow when the buffer is filled to the maximum.

**Comment by lundman** [comment]
hmm yeah, we do need the null, so we will have to +1 on buffers

**Comment by EchterAgo** [comment]
`set_file_link_information`, `delete_entry` & `fastio_query_open` need to be adjusted, `ioctl_query_unique_id` & `mountmgr_is_driveletter_assigned` seem to use the wrong length. I'll need to check where the buffer in `zfs_vnop_lookup_impl` comes from.

**Comment by lundman** [comment]
one up, its 1024 afaik

**Comment by EchterAgo** [comment]
`zfs_vnop_lookup` also needs the size for `filename` increased by one.

**Comment by lundman** [comment]
Hmm actually, now I think since Unix will include the 0 in filenames, the actual name is max 255, we should do `-1` on the `RtlUnicodeToUTF8N()` calls.

**Comment by lundman** [comment]
5a9a781

**Comment by EchterAgo** [comment]
I just tested with 5a9a781fccd22b3512177fb46f1f4c409d21b34d applied, `rclone` seems happy so I'm closing this.
