### ISSUE TITLE
Driver crashing everytime during unload/uninstallation

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#26]
Function spl_kmem_thread_fini() calls bsd_untimeout() passing the nullptr argument(0 hardcoded) which is dereferenced.

void spl_kmem_thread_fini(void) 
{
     bsd_untimeout(kmem_update,  0);
}

![image](https://user-images.githubusercontent.com/84957265/124948981-cef1c280-e02e-11eb-8e88-4aec7875e197.png)

**Comment by datacore-rm** [comment]
File: include/os/windows/spl/sys/wmsum.h

I think there is typo in 'wmsum_t' type definition. So the pointer is not having the allocated memory address.
 
#define	wmsum_t	uint64_t
should be
typedef uint64_t* wmsum_t;

**Comment by lundman** [comment]
3abfd80
be7dcd3
