### ISSUE TITLE
rclone copy succeeds but rechecks some files on second try

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#260]
When I copy a big source dataset using `rclone sync -P` to a dataset, initially there are no errors or warnings. When retrying the same command there are always (seemingly random?) files that are re-checked. This check never finds a difference in the files data, but causes `rclone` to update the files timestamp. Repeating the same `rclone` command again finds no differences.

**Comment by lundman** [comment]
Don't know rclone's internal, but if:

1) filesizes mismatch - but probably not the issue, you say it doesn't move 2nd go
2) lastwrite dates mismatch, or any of a/c/m/w dates mismatch - could be our "set date" has a bug? harmless but should be fixed.
3) something else triggers it? expects xattrs to be in a particular order? ntfs has an order, zfs does not.

**Comment by EchterAgo** [comment]
Modification time seems to have not been set correctly. I'll see if I can get a reproducer for this somehow.

```
2023-08-07 13:11:38 DEBUG : file1.bin: Modification times differ by 2828h12m56.076595s: 2023-04-10 20:41:16.1879049 +0700 +07, 2023-08-06 16:54:12.2644999 +0700 +07
2023-08-07 13:11:39 DEBUG : file2.bin: Modification times differ by 38198h15m59.414203s: 2019-03-29 02:33:22 +0700 +07, 2023-08-06 16:49:21.414203 +0700 +07
```

**Comment by lundman** [comment]
thats quite a difference, so not a "forget to update the final write" but more of a "yeah didnt set the date at all"

**Comment by lundman** [comment]
ok `test.exe fileinfo` agrees there are issues

```
Query basic information, PASS
Set LastWriteTime to -1, PASS
Write to file, PASS
Query basic information, FAIL (ChangeTime was unchanged)
Set ChangeTime to -1, PASS
Write to file, PASS
Query basic information, PASS
Set LastWriteTime to -2, PASS
Write to file, PASS
Query basic information, FAIL (LastWriteTime was unchanged)
Set ChangeTime to -2, PASS
Write to file, PASS
Query basic information, FAIL (LastWriteTime was unchanged)
Set CreationTime, PASS
Query basic information, PASS
Set LastWriteTime, PASS
Query basic information, PASS
Set ChangeTime, PASS
Query basic information, FAIL (ChangeTime was 133359294127868238, expected 128790414900000000)
Open file without FILE_READ_ATTRIBUTES, PASS
```

**Comment by EchterAgo** [comment]
Yea, this looks like the same problem, time not updating. I've also seen files where attributes are not changed.

**Comment by lundman** [comment]
e9881b3

At least the tests look better:

```
Testing on unknown filesystem.
Running test fileinfo
Create file, PASS
Query basic information, PASS
Set times and attributes to 0, PASS
Check times and attributes unchanged, PASS
Write to file, PASS
Query basic information, PASS
Set LastWriteTime to -1, PASS
Write to file, PASS
Query basic information, PASS
Set ChangeTime to -1, PASS
Write to file, PASS
Query basic information, PASS
Set LastWriteTime to -2, PASS
Write to file, PASS
Query basic information, PASS
Set ChangeTime to -2, PASS
Write to file, PASS
Query basic information, PASS
Set CreationTime, PASS
Query basic information, PASS
Set LastWriteTime, PASS
Query basic information, PASS
Set ChangeTime, PASS
Query basic information, PASS
Open file without FILE_READ_ATTRIBUTES, PASS
Try to query basic information, PASS
Open file without FILE_WRITE_ATTRIBUTES, PASS
Try to set basic information, PASS
Open file, PASS
Set hidden flag, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_NORMAL, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_NORMAL | FILE_ATTRIBUTE_READONLY, PASS
Query basic information, PASS
Try to set attributes to FILE_ATTRIBUTE_DIRECTORY, PASS
Set attributes to FILE_ATTRIBUTE_REPARSE_POINT, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_SPARSE_FILE, PASS
Query basic information, PASS
Create directory, PASS
Set hidden flag, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_NORMAL, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_NORMAL | FILE_ATTRIBUTE_READONLY, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_DIRECTORY, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_REPARSE_POINT, PASS
Query basic information, PASS
Set attributes to FILE_ATTRIBUTE_SPARSE_FILE, PASS
Query basic information, PASS
Passed 53/53
```

**Comment by EchterAgo** [comment]
Ok, I tried again with this and the issue is still there. I think I just found something interesting though. Initially after the copy the modification time is correct. When I just `dir /s` the destination folder directly after the copy and then `dir /s` again a few seconds later, the files will switch back to the current date. It looks like there is some background process updating the times. I've also traced this with FileSpy and haven't seen any other process access.

I can very easily produce this now by just copying a bunch of small files (673 files, 256MB) around using `rclone sync -P --filter "- System Volume Information/**" --filter "- $RECYCLE.BIN/**" -v <source> <dest>`. I'll see if I can make a reproducer now.

This is how rclone copes files and sets timestamps:

* Create a file named like the original but with `.partial` suffix in the destination
* Do preallocation if enabled
* Write data
* Read data
* Close `.partial`
* Open `.partial`
* Set timestamps
* Close `.partial`
* Open `.partial`
* Query attribute tag, whatever that is
* Create output file
* Set file rename information
* Close everything

**Comment by EchterAgo** [comment]
Actually, my previous test fails with every item now when used like this:

```powershell
$numitems = 1000

$timestamp = Get-Date (Get-Random -Minimum 0 -Maximum 3155378975999999999)

For ($i=0; $i -lt $numitems; $i++) {
    $name="bla$i"
    "$timestamp" | Out-File -Filepath "$name.partial"
    (Get-ChildItem "$name.partial").LastWriteTime = $timestamp
    Rename-Item -Path "$name.partial" -NewName "$name"
}

Start-Sleep 5

For ($i=0; $i -lt $numitems; $i++) {
    $item = Get-ChildItem "bla$i"
    If ($item.LastWriteTime -ne $timestamp) {
        Write-Host "Mismatch in $i"
    }
    Remove-Item "bla$i"
}
```

**Comment by EchterAgo** [comment]
I think this test passed before the latest changes, but I'll try it again to make sure. 

Anyway, the test succeeds on NTFS and on a Linux ZFS but fails on latest `development` branch.

**Comment by EchterAgo** [comment]
It seems that the timestamps are correct after copying but then get set to the current time a few seconds after the copy finished.

**Comment by EchterAgo** [comment]
Small reproducer:

```
$timestamp = Get-Date 0 -Year 2019

$name = "test"

Remove-Item -Path "$name.partial" -ErrorAction SilentlyContinue
Remove-Item -Path "$name" -ErrorAction SilentlyContinue
"$timestamp" | Out-File -Filepath "$name.partial"
(Get-ChildItem "$name.partial").LastWriteTime = $timestamp
Rename-Item -Path "$name.partial" -NewName "$name"
If ((Get-ChildItem "$name").LastWriteTime -eq $timestamp) {
    Write-Host "Match"
}
Start-Sleep 5
If ((Get-ChildItem "$name").LastWriteTime -ne $timestamp) {
    Write-Host "Mismatch"
}
```

**Comment by lundman** [comment]
Hmm so correct until txg sync happens maybe,  which happens every 5s. Can be tuned of course, or, `zpool sync` to make it happen immediately.

Does this behavior still affect rclone?

**Comment by EchterAgo** [comment]
Yes, it does affect rclone. After the initial rclone run I can rerun rclone a couple of times and it will copy different files each time. I think the 5s time window is likely correct, I can try to measure it if it helps.

**Comment by lundman** [comment]
ok I added the skip-updating-time to the write call, I'll need to chase down the sync one and skip it as well.

**Comment by lundman** [comment]
Hmmm which one is it.

Updates on `zfs_freesp()` but surely it's not shortening the file that often.
Adding to dir, or removing from dir, updates the dir. But I think we are looking at files here.
set_attr of course, but why would it call to set attrs if its disabled time keeping.

**Comment by lundman** [comment]
Oh shit son, there's a producer - ok lets see which one it is

**Comment by lundman** [comment]
It is from this code:
```
#ifdef _WIN32
	/* Windows addition, skip update of Write and Change if requested */
	if (!(uio->uio_extflg & SKIP_WRITE_TIME)) {
		SA_ADD_BULK_ATTR(bulk, count, SA_ZPL_MTIME(zfsvfs), NULL,
		    &mtime, 16);
	}
	if (!(uio->uio_extflg & SKIP_CHANGE_TIME)) {
		SA_ADD_BULK_ATTR(bulk, count, SA_ZPL_CTIME(zfsvfs), NULL,
		    &ctime, 16);
	}
#else
```

In that windows uses `lazy write` which comes in a bit later, and since this is a fresh open, it does not have `SKIP_CHANGE_TIME` set.  Pretty sure everyone stores the bits in `CCB` but something else too?

**Comment by lundman** [comment]
30fb546

**Comment by EchterAgo** [comment]
I just tested with https://github.com/openzfsonwindows/openzfs/commit/30fb5460f4d4aa39f6ace12eff6ea13e0a506ea3 and the issue seems to be fixed. Closing.
