### ISSUE TITLE
Data Miscompare/validation Error

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#27]
Running the data validation tools on a openzfs zvol reports miscompare error. It runs successfully on ZFSin.

steps to reproduce:-
1) create a zpool and zvol
2) Execute any performance measurement tool such as Oracle vdbench on the zvol with data validation enabled (-vr switch in the command line)
3) It reports validation error ie data written and read are not matching.

Please let me know if you need any additional details.

**Comment by lundman** [comment]
fix ok? close?

**Comment by datacore-rm** [comment]
Yes, can close
