### ISSUE TITLE
CrystalDiskMark causes BSOD

### ISSUE THREAD

**Issue by 0x1337F00D** [openzfsonwindows/openzfs#276]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows
Distribution Version	| 11
Kernel Version	| 23550
Architecture	| x64
OpenZFS Version	| zfswin-2.2.0rc4

### Describe the problem you're observing

Hey @lundman,

thanks for your cool project. I tried it out on a usb using the command `zpool create -o dedup=on -O encryption=aes-256-gcm -O keyformat=passphrase -O compression=zstd usb \\?\PhysicalDrive3`. Installing a benchmarktool, CrystalDiskMark in my case, and running all tests results in a BSOD crash within seconds. Caused by `OpenZFS.sys`.

### Describe how to reproduce the problem

Just mount the pool and run all benchmarks via top left button. Writes some temp files to the pool, crashes every time.
### Include any warning/errors/backtraces from the system logs
- I have a minidump if needed
- SYSTEM_SERVICE_EXCEPTION is the error code

**Comment by lundman** [comment]
```
 	nt!KiPageFault+0x43d	C/C++/ASM
>	OpenZFS!fsDispatcher+0x1a77 [C:\src\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 7172] 	C/C++/ASM
 	OpenZFS!dispatcher+0x292 [C:\src\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 7266] 	C/C++/ASM
 	nt!IofCallDriver+0x55	C/C++/ASM

			if (CcIsFileCached(IrpSp->FileObject)) {

IrpSp->FileObject == NULL.

```

curious

**Comment by lundman** [comment]
8c4dc7f

**Comment by EchterAgo** [comment]
@0x1337F00D you might want to try this with RC6, I don't get any more crashes. You can close the issue if it works now.
