### ISSUE TITLE
Some files transfer over and over again when copying with rclone

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#277]
I haven't figured out yet what is happening yet, but when checking which files need copying `rclone` seems to think that always the same files are not there in the destination.

```
2023-09-26 14:05:04 DEBUG : file.bin: Need to transfer - File not found at Destination
2023-09-26 14:05:04 DEBUG : file.bin: md5 = b1551f2c7fdd291699479eae12283893 OK
2023-09-26 14:05:04 DEBUG : file.bin.hokuqon3.partial: renamed to: file.bin
2023-09-26 14:05:04 INFO  : file.bin: Copied (new)
```

I'll try to get `FileSpy` logs for this. I'm seeing this in many directory, but only a few files. This is a directory with 62 files and only 2 of them have this issue.

Everything shows the file as present in the destination and using `HxD` or `md5sum` to compare the files shows them as identical, however the MD5 does not match what `rclone` is logging.

**Comment by EchterAgo** [comment]
Somehow couldn't get FileSpy to log the directory listing results, but Sysinternals Process Monitor did it.

For some reason `QueryDirectory` by `rclone` does not return the 2 files, but for Windows Explorer it returns them.

`rclone` needs 3 `QueryDirectory` while Windows Explorer does them all at once. What I just noticed when comparing the results is that the missing files would have been just between the 1st and 2nd and the 2nd and 3rd calls to `QueryDirectory`. It looks like there is some off-by-one error when using multiple calls to list a directory.

Did we change anything about directory listing recently? I've never seen this error before..

**Comment by lundman** [comment]
Ah interesting - sounds like its new (as opposed to regression) to us. FileSpy might help, if it says "not found" be curious what it bases that on. 

Don't forget that with QueryDirectory, the caller supplies a buffer (of whatever length they feel like). So a large buffer would fit all entries. Smaller would then "fit as many as there is room" then it has to call it again for the "next batch". 

There is a bunch of alignment, offset, spacing, etc math. So yeah, definitely could be an issue there. Also, the difference between STATUS_SUCCESS return, and STATUS_NO_MORE_FILES. 

I believe if we can fit "at least one", we will always return SUCCESS. Then when we are to return 0, as there are no more, we return STATUS_NO_MORE_FILES. I believe that is correct.

FileTest.exe from the same place as FileSpy lets you test QueryDirectory with different buffer sizes etc.

**Comment by EchterAgo** [comment]
So explorer does query the directory without a filter and gets all the 62 files + `.` and `..` in return.

Rclone does query with `*` as filter, gets returned `.` in the first call, `..` + 23 items in the second call, 25 items in the third call and 12 items in the fourth call and `STATUS_NO_MORE_FILES` in the fifth and sixth (why?) call.

When I compare the returned list the missing items would have been just after the 23rd item and after the 48th item.

**Comment by lundman** [comment]
`*` and (nothing) and treated the same, so we should be able to ignore that.

But why just return "." on the first call, I don't think you can see the buffer size with FileSpy, it is in `IrpSp->Parameters.QueryDirectory.Length`

**Comment by lundman** [comment]
Hmm if you have a list of files names (dont need the file data) and we can figure out the buffer size it uses to call, I can probably debug it locally

**Comment by EchterAgo** [comment]
I can send you the Process Monitor capture by email if that helps. I'm trying to catch this in the debugger to get the sizes, otherwise I'd have to check `rclone` / `go` sources, and I'm terrible at `go`.

**Comment by lundman** [comment]
You can also just break into debugger, save the cbuf. Inside is
```

FFFF800E1E035080: dprintf: zfs_vnops_os.c:1329:zfs_readdir(): +zfs_readdir: Inde
x 0, Restart 1, Single 0

FFFF800E1E035080: dprintf: zfs_vnops_windows.c:4219:query_directory_FileFullDirectoryInformation(): dirlist information in 65536 out size 1030
```
So, called with buffer of size 65536, we returned 1030. It was told to restart.

**Comment by EchterAgo** [comment]
No luck getting to cbuf before it gets overwritten so far. Somehow I can't get the debugger to set a breakpoint.

**Comment by EchterAgo** [comment]
Got the debugger breaking now.

1. First call has `SL_RETURN_SINGLE_ENTRY` is set, which is why it returns a single entry. Its `IrpSp->Parameters.QueryDirectory.Length` is 0x268 bytes, which comes from `FindFirstFileExW` which `rclone` uses. At the end `zccb->dirlist_index` is 1.
2. Second call does not have `SL_RETURN_SINGLE_ENTRY` set. Its `IrpSp->Parameters.QueryDirectory.Length` is 0x1000 bytes, which comes from `FindNextFileW`. At the end `zccb->dirlist_index` is assigned a large value from `ctx.offset`

I haven't got any further yet, the debugger crashed :\

**Comment by EchterAgo** [comment]
The other calls look the same as the second.

```
The other calls look the same as the second.

```
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4097:query_directory_FileFullDirectoryInformation(): query_directory_FileFullDirectoryInformation: starting vp FFFFE58D6479F848 Search pattern '*' type 3: saved search '(null)'
FFFFEAD6AD08D080: dprintf: zfs_vnops_os.c:1329:zfs_readdir(): +zfs_readdir: Index 0, Restart 0, Single 1

FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4219:query_directory_FileFullDirectoryInformation(): dirlist information in 616 out size 96
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:7242:dispatcher(): dispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY): type 0x6: fo FFFFE58D8382EBD0
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:6730:fsDispatcher():   fsDispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY) fsDeviceObject
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4097:query_directory_FileFullDirectoryInformation(): query_directory_FileFullDirectoryInformation: starting vp FFFFE58D6479F848 Search pattern '(null)' type 3: saved search '(null)'
FFFFEAD6AD08D080: dprintf: zfs_vnops_os.c:1329:zfs_readdir(): +zfs_readdir: Index 0, Restart 0, Single 0

FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4219:query_directory_FileFullDirectoryInformation(): dirlist information in 4096 out size 4024
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:7242:dispatcher(): dispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY): type 0x6: fo FFFFE58D8382EBD0
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:6730:fsDispatcher():   fsDispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY) fsDeviceObject
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4097:query_directory_FileFullDirectoryInformation(): query_directory_FileFullDirectoryInformation: starting vp FFFFE58D6479F848 Search pattern '(null)' type 3: saved search '(null)'
FFFFEAD6AD08D080: dprintf: zfs_vnops_os.c:1329:zfs_readdir(): +zfs_readdir: Index 0, Restart 0, Single 0

FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4219:query_directory_FileFullDirectoryInformation(): dirlist information in 4096 out size 3972
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:7242:dispatcher(): dispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY): type 0x6: fo FFFFE58D8382EBD0
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:6730:fsDispatcher():   fsDispatcher: enter: major 12: minor 1: IRP_MJ_DIRECTORY_CONTROL(IRP_MN_QUERY_DIRECTORY) fsDeviceObject
FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4097:query_directory_FileFullDirectoryInformation(): query_directory_FileFullDirectoryInformation: starting vp FFFFE58D6479F848 Search pattern '(null)' type 3: saved search '(null)'
FFFFEAD6AD08D080: dprintf: zfs_vnops_os.c:1329:zfs_readdir(): +zfs_readdir: Index 0, Restart 0, Single 0

FFFFEAD6AD08D080: dprintf: zfs_vnops_windows.c:4219:query_directory_FileFullDirectoryInformation(): dirlist information in 4096 out size 1888
```

**Comment by lundman** [comment]
OK if we have the names in a dir, the calls and buffer size can be simulated with FileTest.exe to see what it does wrong.

**Comment by lundman** [comment]
Hmm ok FileTest.exe is a bit useless, sure you can set buffer size, and query the directory, but there is no way to continue the dirlisting, that I can see.

**Comment by lundman** [comment]
Oh you know what, I bet if you comment these two lines out, it works?

https://github.com/openzfsonwindows/openzfs/blob/zfs-Windows-2.2.0-release/module/os/windows/zfs/zfs_vnops_os.c#L1482-L1483

**Comment by EchterAgo** [comment]
I thought about that too and tried setting a breakpoint there, but it was not hit. I'm not sure I set up the breakpoint correctly though.

I'll check what happens when I take them out.

**Comment by EchterAgo** [comment]
That seems to have fixed it. I'll give it some more testing.

**Comment by EchterAgo** [comment]
First call returns 1 item, second call 24, third call 25 and fourth call returns 14, total 64 - 2 (`.` and `..`) = 62 which is the correct number for the folder I'm testing.

**Comment by lundman** [comment]
Yeah, so I had to put those in or ifstest.exe runs forever because it is stupid.

Let me see if I can make it less generic

**Comment by lundman** [comment]
Hmm removed the 2 lines here to confirm ifstest.exe hangs, then to bring them back in a "if (ctx->outcount ==0)" or similar, only to discover ifstest (nor btrfs test.exe) hang anymore. I guess some other thing we fixed must have cleared it.

So the good news is, we can just remove the hack.

**Comment by lundman** [comment]
On breakpoints - something that took me a while to realise, you have to BreakAll, then place a BreakPoint, then Continue. If you place one while it is running, it just pretends to be there.

**Comment by EchterAgo** [comment]
It seems that `ifstest.exe` never really got the `ENOSPC` return anyway, it gets turned into `STATUS_SUCCESS` by the caller.

**Comment by lundman** [comment]
oh hah, that would do it - thanks

**Comment by lundman** [comment]
Hmm no it gets turned into a STATUS_BUFFER_TOO_SMALL at the higher end, no?

**Comment by EchterAgo** [comment]
From `query_directory_FileFullDirectoryInformation`:

```
	} else if (ret == ENOSPC) {

		/*
		 * If we have no "outcount" then buffer is too small
		 * for the first record. If we do have "outcount", we
		 * return what we have, and wait to be called again.
		 */
		if (ctx.outcount > 0)
			ret = 0;
		else {
			Status = STATUS_BUFFER_OVERFLOW;
			zccb->dirlist_index = ctx.offset;
		}
	}
```

IIUC, when there are output items, it gets turned into 0.

**Comment by lundman** [comment]
yeah if we fit 4, 5 or whatever, then we say SUCCESS, cos there are 4, 5 entries in there. They call again to get more.
If we have no entries at all, and ran out of space (!) then it is a serious issue

**Comment by EchterAgo** [comment]
Well, the issue seems fixed, closing.

**Comment by lundman** [comment]
d9e58829280164db9392c857398066a4d1aeb4b3
