### ISSUE TITLE
Stall during rclone check

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#280]
This could be related to changes in #274

So I can copy a few TB of data without stall now, but when doing `rclone check` to verify the copy things slow down first and then stop completely. Interestingly the filesystem is still kind of usable by other processes.

There is a lot of this in cbuf:

```
FFFFB0050D9DD040: vnode_recycle_int: FFFFBAAD1985B740 still has CcMgr, lingering on dead list.
FFFFB0050D9DD040: dprintf: zfs_vnops_windows.c:7861:fastio_acquire_for_mod_write(): fastio_acquire_for_mod_write: 
FFFFB0050D9DD040: dprintf: zfs_vnops_windows.c:7878:fastio_acquire_for_mod_write(): fastio_acquire_for_mod_write: returning STATUS_SUCCESS
FFFFB0050D9DD040: dprintf: zfs_vnops_windows.c:7889:fastio_release_for_mod_write(): fastio_release_for_mod_write:
FFFFB0050D9DD040: already marked
```

and it seems the `FFFFBAAD1985B740` thread does not actually exist. Also scanning for locks takes a really long time.

[cbuf.txt](https://github.com/openzfsonwindows/openzfs/files/12754505/cbuf.txt)
[stacks.txt](https://github.com/openzfsonwindows/openzfs/files/12754507/stacks.txt)
[locks_FFFFB0050D9DD040.txt](https://github.com/openzfsonwindows/openzfs/files/12754510/locks_FFFFB0050D9DD040.txt)

**Comment by EchterAgo** [comment]
Oh, I see, `FFFFBAAD1985B740` is a `vnode` address.

**Comment by lundman** [comment]
Hmm this one will be tricky. So:

```
FFFFB0050F3E9040: dprintf: zfs_vnops_windows.c:5315:fs_write(): zp == NULL
FFFFB0050F3E9040: zfs_vnops_windows.c:5316:fs_write(): error 3221225485
```

We have already "released" zp from the vnode (by calling zfs_vnop_reclaim() some time back) so write() errors out, and the vnode is marked as DEAD. So the messages "already marked" means that, its already marked DEAD when we are trying to mark it DEAD again.
But we cant release the vnode yet "still has CcMgr" - which we have evidence of as Windows keeps calling `fastio_acquire_for_mod_write()` and occasionally `IRP_MJ_WRITE`. Although it is at least 3 different threads endlessly spinning here.

cbuf does not go far enough back to tell us what actually happened, but it'd be pretty noisy to see even if it did.

**Comment by lundman** [comment]
Of the locks, 3 threads are paged out, so possibly supposed to be long-term locks, the one active is `ffffbaacf9604080`

``` [ffffb0051446a080 rclone.exe]
186c.0020d0  ffffbaacf9604080 0000001 RUNNING    +0xfffff8030e62100e
                                        +0xffffb0050b932e80
                                        +0xfffff8030e6246a9
                                        +0xfffff8030e633a68
```

which isn't saying much :)

Not sure how we should approach this. You can view zp and vnodes with `"dt vnode FFFFBAAD1985B740"` and similarly `dt znode` but at least one thread has it as NULL.

I wonder if we are allowed to signal in `zfs_AcquireForLazyWrite()/fastio_acquire_for_mod_write()` that the file is dead

**Comment by EchterAgo** [comment]
I think it is likely 4 threads, that is how many rclone parallel copies I use and they are all stalled. I can produce the problem reliably so we could set a breakpoint somewhere to get more info. I wonder why it is in `fs_write` though, at that point rclone should only be reading from the dataset.

**Comment by EchterAgo** [comment]
```
0: kd> dt vnode FFFFBAAD1985B740
OpenZFS!vnode
   +0x000 FileHeader       : _FSRTL_ADVANCED_FCB_HEADER
   +0x058 AdvancedFcbHeaderMutex : _FAST_MUTEX
   +0x090 SectionObjectPointers : _SECTION_OBJECT_POINTERS
   +0x0a8 oplock           : (null) 
   +0x0b0 v_mutex          : kmutex
   +0x0e0 v_mount          : 0xffffb557`e2b39e80 mount
   +0x0e8 v_parent         : (null) 
   +0x0f0 v_data           : (null) 
   +0x0f8 v_reparse        : (null) 
   +0x100 security_descriptor : (null) 
   +0x108 v_flags          : 0x22
   +0x10c v_iocount        : 0
   +0x110 v_usecount       : 0
   +0x114 v_type           : 1
   +0x118 v_unlink         : 0
   +0x11c v_unused         : 0
   +0x120 v_reparse_size   : 0
   +0x128 v_id             : 0x176b4
   +0x130 v_easize         : 0
   +0x138 v_age            : 0n0
   +0x140 resource         : _ERESOURCE
   +0x1a8 pageio_resource  : _ERESOURCE
   +0x210 lock             : _FILE_LOCK
   +0x270 share_access     : _SHARE_ACCESS
   +0x290 v_list           : list_node
   +0x2a0 v_fileobjects    : avl_tree
```

**Comment by lundman** [comment]
Windows does write to its cache, then the LazyWriter comes along later to sync it out to us. So it could simply be that, rclone has moved into Checking/reading, but Windows is still calling LazyWrite. Which should just work, but for some reason zfs has released the zp, so did a file get deleted? or what other reason we might have called reclaim. 

We can return FALSE in `fastio_acquire_for_mod_write` when zp == NULL, this will force it to call the full WRITE, and possibly detect the error we return.
If we do the same for `zfs_AcquireForLazyWrite()` I am worried the thread will just retry forever.

That vp is indeed completely idle. Might still have SectionObjectPointers pointers != NULL, but it certainly is not in use.

**Comment by lundman** [comment]
but you dont have a single thing doing reads, that does seem odd as well.

**Comment by lundman** [comment]
You could break at 
https://github.com/openzfsonwindows/openzfs/blob/zfs-Windows-2.2.0-release/module/os/windows/zfs/zfs_vnops_windows.c#L5330
and if we are lucky, there wont be too many false-negatives triggered.

**Comment by EchterAgo** [comment]
Now that I want to produce the issue it doesn't want to happen :\ I did update to your latest pagefile changes though, maybe that changed something.

**Comment by EchterAgo** [comment]
Ok, I can produce this now, I do it by selecting a 4GB file in explorer, hitting CTRL+C then CTRL+V a bunch of times, then I press Escape in the copy dialog to cancel all, then the breakpoint in `zfs_vnops_windows.c:5330` is hit.
[cbuf.txt](https://github.com/openzfsonwindows/openzfs/files/12792117/cbuf.txt)

**Comment by EchterAgo** [comment]
Hmmm, sorry, I think in the above I forgot to actually run the background copy which stalls, the system recovered after continuing there. I'll try again.

**Comment by lundman** [comment]
Sorry for the delay, I was in FileAttrivute hell. I did a quick bf5e2c5 to at least detect the NULL zp sooner, maybe it will help.

**Comment by EchterAgo** [comment]
I can definitely produce the stall quickly now by doing the multiple copies and aborting them, I just can't find a good way to break because a breakpoint on `zfs_vnops_windows.c:5330` breaks already when aborting the copies. What I noticed is that such a breakpoint triggers over and over again for quite some time after aborting the copy.

I also had quite a few copy runs without any issue when not touching anything, which makes me wonder whether it is actually the VMWare shared folder source or my servers network share that stops when I stay on a breakpoint for too long. I guess I should test that too.

I'll start testing with bf5e2c58d2b1ec3fdf4c6a37fc9dc50f8d2003c9 now.

**Comment by lundman** [comment]
Hmm that seems worse, even I get LazyAcquire non-stop as it desperately tries to write something,

**Comment by lundman** [comment]
OK so fd8bf0d has large changes again, slightly different area but related. Many tests now pass, so it is more correct but could have regression in it. Since if you miss a cache_init call, it will BSOD unforgivingly.

**Comment by EchterAgo** [comment]
Thanks, that seems to have done it. I'll give this a bunch of testing today.

**Comment by lundman** [comment]
Huh surprising but nice. reopen if it comes back
