### ISSUE TITLE
File sizes are always padded to the next 512 byte boundary

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#281]
Testing with fd8bf0d2b92d18b818505413bb7dd8e75fc8decd

File sizes are always padded to the next 512-byte boundary but files that already have a 512-byte divisible size are copied successfully.

```
2023/10/07 16:44:59 ERROR : files.txt.xz.xomelen9.partial: corrupted on transfer: sizes differ 1938156 vs 1938432
2023/10/07 16:44:59 INFO  : files.txt.xz.xomelen9.partial: Removing failed copy
2023/10/07 16:45:00 ERROR : kloesse.mp4.nijuqoy8.partial: corrupted on transfer: sizes differ 2570501 vs 2570752
2023/10/07 16:45:00 INFO  : kloesse.mp4.nijuqoy8.partial: Removing failed copy
2023/10/07 16:45:00 ERROR : mark.sh.tamunif7.partial: corrupted on transfer: sizes differ 201 vs 512
2023/10/07 16:45:00 INFO  : mark.sh.tamunif7.partial: Removing failed copy
2023/10/07 16:45:00 ERROR : nswcopy.cmd.rofomov1.partial: corrupted on transfer: sizes differ 454 vs 512
2023/10/07 16:45:00 INFO  : nswcopy.cmd.rofomov1.partial: Removing failed copy
2023/10/07 16:45:01 ERROR : test - Copy.otxml.soniweg4.partial: corrupted on transfer: sizes differ 2664 vs 3072
2023/10/07 16:45:01 INFO  : test - Copy.otxml.soniweg4.partial: Removing failed copy
2023/10/07 16:45:01 ERROR : test.cmd.jujikuh9.partial: corrupted on transfer: sizes differ 117 vs 512
2023/10/07 16:45:01 INFO  : test.cmd.jujikuh9.partial: Removing failed copy
2023/10/07 16:45:01 ERROR : test.otxml.zolizoj5.partial: corrupted on transfer: sizes differ 1735 vs 2048
2023/10/07 16:45:01 INFO  : test.otxml.zolizoj5.partial: Removing failed copy
2023/10/07 16:45:03 ERROR : weekend.mp4.jutorah4.partial: corrupted on transfer: sizes differ 21960306 vs 21960704
2023/10/07 16:45:03 INFO  : weekend.mp4.jutorah4.partial: Removing failed copy
2023/10/07 16:45:04 ERROR : Downloads/desktop.ini.fefulax8.partial: corrupted on transfer: sizes differ 278 vs 512
2023/10/07 16:45:04 INFO  : Downloads/desktop.ini.fefulax8.partial: Removing failed copy
```

**Comment by EchterAgo** [comment]
All the files that were actually copied ere disk images, so they are multiples of 512 in size.

**Comment by lundman** [comment]
ah ok yeah, so allocationsize is padded up - but i guess sometimes I shoudnt. it doesnt actually grow the file tho

**Comment by EchterAgo** [comment]
It does seem to report file size in the file properties correctly:

![image](https://github.com/openzfsonwindows/openzfs/assets/922233/8b4e6f70-e51b-48e7-8a79-092e7e3b6490)

**Comment by EchterAgo** [comment]
[procmon_capture.zip](https://github.com/openzfsonwindows/openzfs/files/12837410/procmon_capture.zip)

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/openzfs/blob/zfs-Windows-2.2.0-release/module/os/windows/zfs/zfs_vnops_windows.c#L306

basically, instead of `a` here, if we use `s` it will not be rounded up. I'll try that with the test.exe tomorrow to see if it would still pass.

**Comment by EchterAgo** [comment]
It seems to me that the value that is being checked comes from here:

https://github.com/openzfsonwindows/openzfs/blob/fd8bf0d2b92d18b818505413bb7dd8e75fc8decd/module/os/windows/zfs/zfs_vnops_windows_lib.c#L4549

`z_size` is actually 512, but when I change `netopen->EndOfFile.QuadPart` to the actual file size using the debugger, the copy succeeds but a later dir shows the file as 512 bytes:

```
04/10/2023  08:06 PM               512 test.cmd
```

This seems to be somehow triggered by how `rclone` writes the file. When I create a file using notepad the file size is correct.

**Comment by lundman** [comment]
ah then z_size IS incorrect.- yeah thats worse.  I'll have to check if the new commit rounds it up somewhere accidentally

**Comment by EchterAgo** [comment]
I think this might come from some preallocation that rclone does. It does `IRP_MJ_SET_INFORMATION` with `FileAllocationInformation AllocationSize 0-200`.

First it only writes the correct amount of data, but a subsequent read then returns the rounded up size.

**Comment by EchterAgo** [comment]
![image](https://github.com/openzfsonwindows/openzfs/assets/922233/8cfb071b-94a1-4eb0-9643-50ed32cd2f1b)

**Comment by lundman** [comment]
ah ok its FileAllocation, calls SetEndOfFile - but shouldnt affect z_size - yeah thats an oversize. if prealloc is set, we shouldnt update size

**Comment by EchterAgo** [comment]
Yea, passing `--local-no-preallocate` also makes it copy successfully:

```
C:\Users\WDKRemoteUser>rclone copy --local-no-preallocate s:\nosnap\refsbak\test.cmd D:
2023/10/07 18:27:58 NOTICE: Config file "C:\\Users\\WDKRemoteUser\\AppData\\Roaming\\rclone\\rclone.conf" not found - using defaults

C:\Users\WDKRemoteUser>dir d:\
 Volume in drive D is Data
 Volume Serial Number is 1983-1116

 Directory of d:\

10/07/2023  06:27 PM    <DIR>          .
10/07/2023  06:27 PM    <DIR>          ..
04/10/2023  08:06 PM               117 test.cmd
               1 File(s)            117 bytes
               2 Dir(s)  11,483,530,155,520 bytes free

C:\Users\WDKRemoteUser>
```

**Comment by lundman** [comment]
ok its not entirely clear what it does when prealloc is set:
https://github.com/maharmstone/btrfs/blob/240692430468e44efdef83b04b57d342e9bf9243/src/fileinfo.c#L3301
which it is when coming from `FileAllocationInformation`.
I'll have to think on it, but first thing to try is only setting AllocationSize is prealloc is true, the rest should remain unchanged:
https://github.com/openzfsonwindows/openzfs/blob/zfs-Windows-2.2.0-release/module/os/windows/zfs/zfs_vnops_windows_lib.c#L3526-L3531

**Comment by EchterAgo** [comment]
I created a test for this issue which should catch this, it tests file sizes directly after preallocation, after write and after close. I ran the same test on NTFS, ReFS and a Samba share and it passes. I'm going to submit it as a PR once I clean it up a bit more.

I'll try modifying `set_file_endoffile_information` now and see if the test passes.

**Comment by EchterAgo** [comment]
I have the current (not yet cleaned up) test here: https://github.com/EchterAgo/zfs/tree/preallocation_test

**Comment by EchterAgo** [comment]
The issue seems to still be there, rclone fails as before and the test fails in all 3 checks:

```
- `AssertionError: 512 != 0 : Wrong file size after preallocation of E:\testfile.bin`
- `AssertionError: 512 != 0 : Wrong file size after write to preallocated file E:\testfile.bin`
- `AssertionError: 512 != 117 : Wrong file size after close of preallocated file E:\testfile.bin`
```

**Comment by EchterAgo** [comment]
I assume you meant to modify the `set_file_endoffile_information` code like this:

```
	vp->FileHeader.AllocationSize.QuadPart = new_end_of_file;
	ccfs.AllocationSize.QuadPart = new_end_of_file;
	if (!prealloc) {
		vp->FileHeader.FileSize.QuadPart = new_end_of_file;
		vp->FileHeader.ValidDataLength.QuadPart = new_end_of_file;
		ccfs.FileSize.QuadPart = new_end_of_file;
		ccfs.ValidDataLength.QuadPart = new_end_of_file;
	}
```

**Comment by EchterAgo** [comment]
I just checked winbtrfs and it has the same issue.

**Comment by EchterAgo** [comment]
I also filed an issue in https://github.com/maharmstone/btrfs/issues/597

**Comment by lundman** [comment]
> I assume you meant to modify the set_file_endoffile_information code like this:

Did this help?

**Comment by EchterAgo** [comment]
No, both rclone and my test fail with the modification, but I'm not sure if it fails in exactly the same way. I can get the exact behaviour without the change if you want.

**Comment by lundman** [comment]
I assume the issue is that `FileAllocationInformation` should not affect FileSize nor ValidDataLength, which it does at HEAD. Curious that the fix didn't work, I'll have a dig around with the tester.

**Comment by EchterAgo** [comment]
Well, I can try again, sometimes my test VM doesn't update the driver well, I have some notes about that too which I might put into an issue. But I tried on both the VM and my host now. I'll try updating `ZFS_META_GITREV` so I can see whether the current code really is on the VM.

**Comment by EchterAgo** [comment]
I double checked now that the right code is on the system, the issue still occurs.

**Comment by EchterAgo** [comment]
Also, if you want a small reproducer, just use rclone to transfer a file < 512 bytes to the volume:

`rclone copy C:\srcfile.bin Z:`

**Comment by EchterAgo** [comment]
Maybe off-topic: Turns out Samba's `smbd` also does not respect the file systems block size correctly, instead using a config option that defaults to 1024, not very usable when you share ext4, btrfs and zfs with different block sizes. So when you query `FS_INFORMATION_CLASS.FileFsSizeInformation` Samba reports wrong values, `SectorsPerAllocationUnit=2` and `BytesPerSector=512` for a filesystem that has 4k blocks 🤦‍♂️

I think in Windows userspace you really should not care too much about the allocation size, maybe I'll make my test only check the expected allocation sizes if not running on a network share.

**Comment by lundman** [comment]
just to catch up, on HEAD:
```
$ dd if=/dev/random of=smol.bin bs=317 count=1
1+0 records in
1+0 records out
317 bytes copied, 0.0013747 s, 231 kB/s

$ ls -l smol.bin
-rw-r--r-- 1 WDKRemoteUser 197121 317 Oct  8 15:23 smol.bin

$ ./rclone-v1.64.0-windows-amd64/rclone.exe copy smol.bin /e/
2023/10/08 15:24:37 ERROR : smol.bin.cizarus8.partial: corrupted on transfer: sizes differ 317 vs 512
```

So I can at least duplicate it :)

**Comment by lundman** [comment]
OK, so restoring `FileAllocationInformation` to what it was before makes `rclone` work as expected.

This is what ChatGPT said about the operation:

***

When you receive an IRP_MJ_SET_INFORMATION with a minor function of FileAllocationInformation, it indeed pertains to changing the value of Header.AllocationSize. This operation is used to set the file's allocated size, which represents the amount of space reserved on disk for the file. It does not change the file's actual content or modify Header.FileSize or Header.ValidDataLength. It's about pre-allocating space on disk for future data writes.

Here's a breakdown of what this operation does:

Header.AllocationSize: This field is updated to reflect the new allocated size for the file. It represents the total space reserved for the file on disk, including both used and unused space. The file system ensures that this allocation size is sufficient to accommodate future writes.

Header.FileSize: This field remains unchanged. It represents the current size of the file, including the actual data stored in the file. Setting the allocation size does not affect this value.

Header.ValidDataLength: This field also remains unchanged. It represents the length of the valid data within the file. Changing the allocation size does not alter this value or the existing file content.

File Data: The operation does not truncate or extend the actual file data. It only pre-allocates space for future writes. Any existing data in the file remains intact.

In summary, IRP_MJ_SET_INFORMATION with FileAllocationInformation is used to modify the allocation size, ensuring that enough space is reserved on disk for future writes without affecting the current file size or content.

***

So we should probably check that if the request is larger than current value, we just update `AllocationSize` and do nothing else. In ZFS we don't really have the concept of pre-allocate space, afaik.

**Comment by lundman** [comment]
***
In the FAT file system, when you request to set a smaller allocation size, FatTruncateFileAllocation can be called to release the excess clusters associated with the file, effectively shrinking the allocated space for the file.

It's important to note that this behavior is specific to the FAT file system, and other file systems like NTFS may have different behavior when it comes to resizing allocated space for a file. When working with different file systems, it's essential to consider their specific characteristics and behaviors regarding space allocation and resizing.
***

Ah interesting. Well, using FileTest it should be straight forward to check how NTFS behaves. Interesting to note that ReactOS also took the approach that SetFileAllocation just calls SetEndOfFile

**Comment by lundman** [comment]
Hah ok, NTFS, starting with 0xA000 file, when you increase AllocationSize +0x2000, will increase only AllocationSize (using StandardInformation to check) to 0xC000. FileSize will not increase, so there is no "extend_file".  
Interestingly, you can add another +0x2000, to get 0xe000. You can decrease AllocationSize back to 0xC000, and StandardInformation will return to 0xC000.  It is not "grow only".

However, if I set AllocationSize to 0x1000, now StandardInformation will reply with AllocationSize==0x1000 AND FileSize==0x1000! So it does indeed truncate_file. Take that chatgpt.

**Comment by lundman** [comment]
1bc536d

thanks for testing this, now FileTest (FileAllocationInformation) behaves the same as NTFS.

**Comment by EchterAgo** [comment]
Thanks, that fixed it. My test still fails though, but for a different reason:

![image](https://github.com/openzfsonwindows/openzfs/assets/922233/4894f5ba-97ae-4bab-b55a-5382a500d1e2)

It seems that after closing the file `GetFileInformationByHandleEx` reports an `AllocationSize` of 0, while the Explorer returns the expected 512.

**Comment by EchterAgo** [comment]
```
*** Assertion failed: 0
***   Source File: H:\dev\openzfs\module\os\windows\spl\spl-seg_kmem.c, line 134
```

got this during my rclone test, which is `ExAllocatePoolWithTag failed`. Sadly I can't seem to get any more info out of the machine, it is stuck. I'm not sure when this happened, but also my cat stepped on the computers power button and shut off the system, only noticed it after. 

Still, so far the tests have been going well, other than the AllocationSize==0 thing.

**Comment by EchterAgo** [comment]
I think we got a memory leak recently, running rclone results in crashes with `ExAllocatePoolWithTag failed` reliably. Not sure if it is related to the changes for this issue but something is going on. Maybe I'll open a separate issue for this. This is the last image from when my VM stopped:

![image](https://github.com/openzfsonwindows/openzfs/assets/922233/1760da2d-05ac-4841-84bd-2ac5f0a1fb44)

I'll check if I can find out which change is causing this.

**Comment by EchterAgo** [comment]
[memory.txt](https://github.com/openzfsonwindows/openzfs/files/12864927/memory.txt)

**Comment by lundman** [comment]
Looks a bit sus, create a new ticket for it. You can also run "kstat.exe" as it will break down each allocation-zone inside ZFS which can help hone in to the issue

**Comment by EchterAgo** [comment]
Done, see #283. Should I also create a separate issue for the remaining test failure https://github.com/openzfsonwindows/openzfs/issues/281#issuecomment-1752388812 or just keep this open?

**Comment by lundman** [comment]
Leave it here, hoping to have a commit soon

**Comment by andrewc12** [comment]
@EchterAgo can you test this again since the test added in #284 passes now
