### ISSUE TITLE
How to upgrade existing ZFS on WIndows installation

### ISSUE THREAD

**Issue by derritter88** [openzfsonwindows/openzfs#292]
### Describe the feature would like to see added to OpenZFS
It would be a nice to have if there would be a guild how to upgrade on WIndows.
Anytime I am not sure if I need to uninstall the old driver first and install the newest release after a reboot or if is okay to just install the new release without removing the old version.

### How will this feature improve OpenZFS?
More detailed instructions directly on the Github manual.

**Comment by sskras** [comment]
Some insights can be found here:
https://github.com/openzfsonwindows/openzfs/discussions/287

**Comment by derritter88** [comment]
Thanks - I'll continue there.
