### ISSUE TITLE
Hard links can fail to delete

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/openzfs#293]
Assume you create a file:
`./connery/sean`
then create a hardlink that points to it named
`./moore/roger`.

Since they are the same data file, the same `znode_t`, but now with `zp->z_links == 2`, it is hard to know which name to reply
with when queried. Currently, when you open `./connery/sean`, we update `zp->z_name_cache`, to `sean` and parent to `connery`.

Likewise for `./moore/roger`., name to `roger` and parent to `moore`. This is inherited from XNU, and how macOS handles hardlinks and `vnop_getattr(VA_NAME);`

This handles 80% of the usage, and since hardlinks on Windows are not-common, it has not caused much of an issue.

The probably is exacerbated on Windows with `FILE_DELETE_ON_CLOSE` which is a `file open` flag. So imagine the sequence:

```
open(`./connery/sean`, FILE_DELETE_ON_CLOSE);
open(`./moore/roger`, 0);
close();
close();
```

The last close will finally deal with `FILE_DELETE_ON_CLOSE`, and `zfs_remove(parent, name-to-delete)` we currently
attempt to delete:
`./connery/roger`
which is not ideal. Potentially, I can probably fool it into deleting the wrong name entirely.

Some extra care will be needed for Windows, we will need to store which hardlink is to be deleted, potentially even store the name used to open the file in ccb, which is unique to each open. Then we can both reply with the correct name, as well as, delete the file they intended to delete.

As for next/prev hardlink, we can probably keep the macOS helper code.

**Comment by lundman** [comment]
In fact which probably makes more sense is to move `zp->z_name_cache` into `ccb`, and could explain why other filesystems store it there. It would also mean `znode_t` goes back to being more like upstream.

Will be a little disruptive, but I think it worth doing.

**Comment by lundman** [comment]
8dafd5a

Fairly large change, moving z_name_cache from znode into zccb (formerly zfs_dirlist_t) node, hopefully there aren't many more large changes. This now means we have the name the file was opened with, which now passes all hardlink tests. We know exactly which name to delete. A bit of extra logic in there to update the name, if a file was already open before a rename request.

**Comment by sskras** [comment]
Wow! I haven't dug into that yet, but is NTFS driver logic for hardlink handling so much different from FS drivers on unices?

**Comment by lundman** [comment]
Nah it is just that you can ask to "delete" it when you open it (so pretty early on) then have other (same) hardlinks open under different names. macOS does things one way, it just didn't vibe with Windows way.
