### ISSUE TITLE
Unable to create partition for drive

### ISSUE THREAD

**Issue by derritter88** [openzfsonwindows/openzfs#294]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 
Distribution Version	| 11
Kernel Version	| 22h2
Architecture	| 64bit
OpenZFS Version	|  2.2.0rc5 

### Describe the problem you're observing
I wanted to try ZFS for my personal data and kicked of NTFS to replace it via ZFS. 
Unfortunately it did not work with error
```
C:\Windows\System32>zpool create -o ashift=12 User PHYSICALDRIVE0                                                       
Expanded path to '\\?\PHYSICALDRIVE0'                                                                                   
working on dev '#1048576#1000194703360#\\?\PHYSICALDRIVE0'                                                              
correcting path: '//./#1048576#1000194703360#//?/PHYSICALDRIVE0'                                                        
cannot create 'User': invalid argument for this pool operation  
```

### Describe how to reproduce the problem
Remove all existing partitions of a drive and use zpool command

### Include any warning/errors/backtraces from the system logs

Was not able to find anything beside the CLI error

**Comment by EchterAgo** [comment]
You could also test whether you can create a file based pool:

```
fsutil file createnew C:\poolfile.bin 200000000
zpool.exe create tank \\?\C:\poolfile.bin
```

**Comment by derritter88** [comment]
@EchterAgo thanks for the input.
I have also tried those commands. Neither worked.

in general I do not want to have a virtual disk file. I wanted to try it the „Linux way“.

Before I tried to migrate I did two backups on two separate drives beside my automatic backups.

**Comment by EchterAgo** [comment]
I know you don't want that, I just suggested testing this to see if pool creation works in general.

**Comment by derritter88** [comment]
I’ll try that tomorrow. Took my an hour to reset my SSD due to Microsoft inability to provide proper system configuration tools…

**Comment by EchterAgo** [comment]
You might want to try:

```
diskpart
select disk 0
clean
exit
```

**Comment by derritter88** [comment]
That would be a good solution. 
I struggled with deleting partition but Windows was not able to do that. Had Tobias a 3rd party tool as a Linux live distribution didn’t boot. Probably due to some specific bios settings…

**Comment by EchterAgo** [comment]
Did you clean the partitions before trying to create the zpool? If there was still an active filesystem on there that might have been the issue.

**Comment by EchterAgo** [comment]
Yea, that sounds good.

**Comment by andrewc12** [comment]
Can I just confirm that you're trying to do this to physicaldrive0?

Can I get you to dump a listing of drives in you computer with

wmic diskdrive list brief

**Comment by derritter88** [comment]
@EchterAgo I have tried the thing with create a local "containter" on my E-drive (poolfilen.bin). This worked without any issues:

```
PS E:\Users\mmuehlbacher\Downloads> fsutil file createnew E:\poolfile.bin 200000000
Die Datei E:\poolfile.bin wurde erstellt.
PS E:\Users\mmuehlbacher\Downloads> zpool.exe create tank \\?\E:\poolfile.bin
```

```
PS E:\Users\mmuehlbacher\Downloads> zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
tank   176M   119K   176M        -         -     1%     0%  1.00x    ONLINE  -
```

Additional I have also tried to create the pool with `-o ashift=12` to match the general 4k structure. This also works.


@andrewc12 
Yes, I tried to use PHYSICALDRIVE0 without any luck.
```
PS E:\Users\mmuehlbacher\Downloads> wmic diskdrive list brief
Caption                       DeviceID            Model                         Partitions  Size
Samsung SSD 970 EVO Plus 1TB  \\.\PHYSICALDRIVE1  Samsung SSD 970 EVO Plus 1TB  1           1000202273280
Samsung SSD 970 PRO 512GB     \\.\PHYSICALDRIVE2  Samsung SSD 970 PRO 512GB     4           512105932800
Samsung SSD 970 EVO 1TB       \\.\PHYSICALDRIVE0  Samsung SSD 970 EVO 1TB       1           1000202273280
```

PHYSICALDRIVE0 would be my "E:" drive where I only store stuff like pictures, documents, downloads.

Not sure if this information is necessary for you or not but all my drives are NVMe drives.

**Comment by derritter88** [comment]
I additional tried several other pool names including the famous "tank".
Nothing worked.

**Comment by lundman** [comment]
Is PHYSICALDRIVE0 listed as "black" in "Disk Manager" ? As in, no volume on it?

**Comment by derritter88** [comment]
Yes, I remove all existing partitions before I tried to create the ZFS volume.
It was totally black

**Comment by andrewc12** [comment]
Hum, why does this say 1 partition? 🤔
> Samsung SSD 970 EVO Plus 1TB  \\.\PHYSICALDRIVE1  Samsung SSD 970 EVO Plus 1TB  1           1000202273280

Can you try running this in PowerShell and sharing the result?
Get-Partition -DiskNumber 0

**Comment by derritter88** [comment]
> Hum, why does this say 1 partition? 🤔
> 
> ```
> PS E:\Users\mmuehlbacher\Downloads> wmic diskdrive list brief
> Caption                       DeviceID            Model                         Partitions  Size
> Samsung SSD 970 EVO Plus 1TB  \\.\PHYSICALDRIVE1  Samsung SSD 970 EVO Plus 1TB  1           1000202273280
> Samsung SSD 970 PRO 512GB     \\.\PHYSICALDRIVE2  Samsung SSD 970 PRO 512GB     4           512105932800
> Samsung SSD 970 EVO 1TB       \\.\PHYSICALDRIVE0  Samsung SSD 970 EVO 1TB       1           1000202273280
> ```
> 
> Can you try running this in PowerShell and sharing the result? Get-Partition -DiskNumber 0

I had to reformat it with NTFS as I needed the files for my work.

**Comment by derritter88** [comment]
I took my free time yesterday to copy everything from the existing drive to a different location. Remove all partitions on PHYSICALDRIVE0 (= E:) and tried to create the ZFS pool

It did not work so I had to format it again with NTFS and copied the files back to the E: drive.

If you want me to test anything I am always happy to do that.

**Comment by lundman** [comment]
Hmm so we lost the way to dump cbuf from userland, should restore that. I checked out WPP, to enable trace etc, but I failed to get it to output anything useful.

zpool.exe with verbose prints would be nice, wonder if that exists on other platforms

**Comment by derritter88** [comment]
Interessting fact I stumbled accross: I formated an external SSD (Samsung T7) with the exact same commands as my E: drive.
This worked without any issues. Only on ZFS on Mac I was not able to mount it due to some missing stuff - nevermind.

But as soon as I wanted to copy stuff to the external SSD I got a BSOD.

**Comment by lundman** [comment]
OK you are saying the original problem of creating a pool is now over, but you get BSOD when you copy data to it? Is this from HEAD or rc5 ?

**Comment by derritter88** [comment]
@lundman 
No, the problem with the internal drive is still there.
I just tried additional to the interal drive to format an external drive with ZFS. The command I used for that was `zpool create -o ashift=12 T7 PHYSICALDRIVE3`

Zpool was visible at the Windows Explorer although it said filesystem NTFS.
I copied over the files from my E drive to the ZFS pool and after some minutes - I wasn't watching to copy progress - my computer BSOD. IIRC the error said something like "openzfs.sys".

_Is this from HEAD or rc5 ?_
I have used the latest installed for that. `zfs version` says
```
zfswin-2.2.0rc5
zfs-kmod-zfswin-2.2.0rc5
```

**Comment by lundman** [comment]
OK we have fixed a ton of things since rc5, I should push out rc6. Anything outstanding for rc6 everyone?

**Comment by EchterAgo** [comment]
Might want to wait a few hours, I want to give the current `zfs-Windows-2.2.0-release` some testing.

**Comment by lundman** [comment]
I was just reminded snapshots are broken, so I need to at least fix basic usage

**Comment by derritter88** [comment]
Interesting fact: I create a zpool on Linux (Proxmox) and exported it there.
Imported in on my Windows machine and was able to enable lz4 compression + encryption.

I am copying files without any BSOD which was not working while I created the zpool directly on Windows.

**Comment by derritter88** [comment]
Right after my last comment my system crashed...
I will try something different now.

**Comment by lundman** [comment]
built from sources? latest rc does have known issue.

**Comment by derritter88** [comment]
No, I am using the releases from Github.
I don't know how to build stuff on Windows - I am more the `make` guy.

So far I figured out that it seems to be an Umlaut-related issue:

`Dämonen` is not working while `Daemonen` is working.

**Comment by derritter88** [comment]
A guess would be that regular copy paste via Explorer throws an error and stops.
Usually I use a tool called `FreeFileSync` which probably handles to copy process different and due to that I get a BSOD.

**Comment by lundman** [comment]
yeah we are close to another rc release that fixes the known copy issues, just got to make sure unmount works

**Comment by derritter88** [comment]
Is Umlaute generally supported by ZFS on Windows?

**Comment by derritter88** [comment]
Interessting fact: I can create folders and files with Umlauts but I cannot copy it from a different location.
New bug?

**Comment by derritter88** [comment]
Another issue:
I have created encrypted datasets for external backups.

Initially this worked without any issues and I was able to copy files over.
zpool export + PC shutdown.

After turning it on again and do a zpool import + decrypting the dataset I cannot access them as Windows is not able to enter the datasets although they are successfully decrypted and key is being loaded.

**Comment by lundman** [comment]
try with normalize=formD

**Comment by derritter88** [comment]
It worked after I mounted one fileset after the other - it didin't work with `-a` option.

**Comment by derritter88** [comment]
It seems it was my mistake when creating a zpool.
