### ISSUE TITLE
Unable to build Release Binaries

### ISSUE THREAD

**Issue by datacore-raj** [openzfsonwindows/openzfs#31]
Showing error ->
<img width="916" alt="Release_build_error" src="https://user-images.githubusercontent.com/64899719/128857831-97b7923f-783b-461d-bd6f-7efbe7444fad.PNG">

Error in ouput ->
<img width="644" alt="ouput_error" src="https://user-images.githubusercontent.com/64899719/128857949-e9b8c254-e8c7-4a03-8a7c-e32d2d7ee67b.PNG">

**Comment by lundman** [comment]
```
#ifdef ZFS_DEBUG
	struct abd	*abd_parent;
	zfs_refcount_t	abd_children;
#endif
```

`	zfs_refcount_create(&abd_zero_scatter->abd_children);`

So mismatch with DEBUG and not. 

AH! So

```
# Unconditionally enable debugging for libzpool
AM_CPPFLAGS += -DDEBUG -UNDEBUG -DZFS_DEBUG
```

we should enable ZFS_DEBUG always in userland libzpool

**Comment by datacore-raj** [comment]
Thanks Jorgen,

Rasied PR with changes https://github.com/openzfsonwindows/openzfs/pull/33

**Comment by lundman** [comment]
Perfect, thanks for sorting that out
