### ISSUE TITLE
Windows does not honor structure

### ISSUE THREAD

**Issue by derritter88** [openzfsonwindows/openzfs#316]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Win 11 23H2
Architecture	| amd64
OpenZFS Version	| zfswin-2.2.0rc5

### Describe the problem you're observing
I created a new ZFS pool and created some ZFS sets
X18                25.0G  16.2T   176K  /X18
X18/Backup         25.0G  16.2T   204K  /X18/Backup
X18/Backup/Folder1   25.0G  16.2T  25.0G  /X18/Backup/Folder1
X18/Backup/Folder2   204K  16.2T   204K  /X18/Backup/Folder2

Within Windows Explorer every ZFS set is shown within the root directory (e.g. F:\).

Is this a bug or the expected behaviour?

### Describe how to reproduce the problem
Create different ZFS sets via `zfs create xxx/yyy`

**Comment by lundman** [comment]
By default I would expect you to see:
```
F:
F:/Backup
F:/Backup/Folder1
F:/Backup/Folder2
```

Which is the default hybrid. Strictly Unix would put `C:/X18` but I figured Windows users wouldn't expect that. This is why `driveletter=poolOnly`. Ie, the pool Dataset (X18) will get a drive letter, and the rest are mounted inside it. You can change `driveletter` property

**Comment by derritter88** [comment]
I didn't look at the CLI - only on the GUI it was kind of a "flat view" (everything within root).

**Comment by lundman** [comment]
Sure, but you should have noticed "Backup" inside is a reparse/symlink folder icon, to indicate something is mounted there.

If you want everything as individual driveletter, which is "flatter", set driveletter=on.

**Comment by derritter88** [comment]
Yes I guessed something like that as the folder icon looked different compared to "regular" folder icons.
Currently I attached the drive to my server running ZFS 2.0.1 to do some backups.

As soon as this has finished I will reinstall the disk to my Windows machine and see how it looks like.
If it still looks weird I'll attach a screenshot of it.

**Comment by lundman** [comment]
I'm curious as to what you expected? Everything inside root (F:) is exactly how Unix would do it, and everything as its own volume would be flat...

**Comment by derritter88** [comment]
This is may layout:
```
root@proxmox2:~# zfs list -r X20
NAME                USED  AVAIL     REFER  MOUNTPOINT
X20                5.40T  10.8T      104K  /X20
X20/Backup         5.40T  10.8T      240K  /X20/Backup
X20/Backup/Filme    211G  10.8T      211G  /X20/Backup/Filme
X20/Backup/Serien  5.20T  10.8T     5.20T  /X20/Backup/Serien
```

And this is how it looks like from CLI perspective:

```
root@proxmox2:~# tree /X20/ -L 2
/X20/
└── Backup
    ├── Filme
    └── Serien
```


On Windows Explorer I just had F: with symlinks 
F:\Backup
F:\Serien
F:\Filme

**Comment by lundman** [comment]
```
# zpool.exe create -O casesensitivity=insensitive BOOM PHYSICALDRIVE1
Expanded path to '\\?\PHYSICALDRIVE1'

# zfs create BOOM/backup

# zfs create BOOM/backup/series

# zfs create BOOM/backup/movies

# zfs mount
BOOM                            E:\
BOOM/backup                     BOOM/backup
BOOM/backup/series              BOOM/backup/series
BOOM/backup/movies              BOOM/backup/movies

$ ls -lR /e/
/e/:
drwxr-xr-x 4 WDKRemoteUser 197121 0 Nov  5 16:54  backup/

/e/backup:
drwxr-xr-x 2 WDKRemoteUser 197121 0 Nov  5 16:54 movies/
drwxr-xr-x 2 WDKRemoteUser 197121 0 Nov  5 16:54 series/

/e/backup/movies:
/e/backup/series:

$ find /e/
/e/
/e/backup
/e/backup/movies
/e/backup/series

```

Try again?

**Comment by derritter88** [comment]
I did that via Powershell on my Windows with a different drive:

```
PS E:\Users\mmuehlbacher\Downloads> zpool create -O casesensitivity=insensitive BOOM PHYSICALDRIVE3
Expanded path to '\\?\PHYSICALDRIVE3'
working on dev '#1048576#4000776716288#\\?\PHYSICALDRIVE3'
setting path here '/dev/physicaldrive3'
setting physpath here '#1048576#4000776716288#\\?\PHYSICALDRIVE3'
PS E:\Users\mmuehlbacher\Downloads> zfs create BOOM/backup
PS E:\Users\mmuehlbacher\Downloads> zfs create BOOM/backup/series
PS E:\Users\mmuehlbacher\Downloads> zfs create BOOM/backup/movies
PS E:\Users\mmuehlbacher\Downloads> zfs mount
BOOM                            F:/
BOOM/backup                     f:/backup
BOOM/backup/series              f:/series
BOOM/backup/movies              f:/movies

PS E:\Users\mmuehlbacher\Downloads> ls F:


    Verzeichnis: F:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l        05.11.2023     09:03                backup
d----l        05.11.2023     09:03                movies
d----l        05.11.2023     09:03                series


PS E:\Users\mmuehlbacher\Downloads> zfs list -r BOOM
NAME                 USED  AVAIL  REFER  MOUNTPOINT
BOOM                 245K  3.51T    37K  /BOOM
BOOM/backup         74.5K  3.51T  24.5K  /BOOM/backup
BOOM/backup/movies  24.5K  3.51T  24.5K  /BOOM/backup/movies
BOOM/backup/series  25.5K  3.51T  25.5K  /BOOM/backup/series
```

**Comment by lundman** [comment]
how neat! I'll look into it

**Comment by derritter88** [comment]
Cheers and what is still curious is the thing with Umlauts.

**Comment by lundman** [comment]
yeah, focus has been on stable - hoping to check in on locale after that.

**Comment by derritter88** [comment]
Would be cool as I'd like to migrate my User drive totally over to ZFS

**Comment by derritter88** [comment]
Right now I had a BSOD with CACHE_MANAGER exception

**Comment by derritter88** [comment]
Right now I had another BSOD with "CACHE_MANAGER" exception.

**Comment by lundman** [comment]
quick tests didnt show any issues, did you make a ticket for it?

<img width="590" alt="localetest" src="https://github.com/openzfsonwindows/openzfs/assets/637168/a0e23e43-ff3a-42ad-a80f-f010cb91109e">

**Comment by derritter88** [comment]
I mentioned it here: #294

**Comment by derritter88** [comment]
The issue is not creating something - this works well - but to copy over stuff with Umlauts.
When I copy something via Explorer sometimes I get an error, sometimes it just hangs infinite.

Usually for backing up my stuff I am using an application called FreeFileSync which compares two folders and mirrors one to the other.
When I use this app I usually get a BSOD with "OpenZFS.sys"

**Comment by derritter88** [comment]
I tried it again: Initially I had a BSOD when I mounted the pool with "CACHE_MANAGER".
After a restart I started copying files on the drive and after some minutes I had another reboot but without any message, just black and reboot.

**Comment by lundman** [comment]
Yes, I need to roll out a rc6 for you, many fixes since rc5

**Comment by derritter88** [comment]
That would be totally awesome!

**Comment by derritter88** [comment]
Do you know when there would be the RC6 version?

**Comment by EchterAgo** [comment]
You could try using a build artifact from https://github.com/openzfsonwindows/openzfs/actions/runs/6757669188 for example. Download the `[dev_build_inno](https://github.com/openzfsonwindows/openzfs/suites/17911136450/artifacts/1028854979)` artifact, it should contain a setup exe.

Note that the artifacts are only signed with a test signing certificate, so you'll have to enable test signing to use them, see https://github.com/openzfsonwindows/openzfs/tree/windows/module/os/windows#installing-a-binary-release

**Comment by derritter88** [comment]
Thanks! I did not know that this is also possible as I usually checked the regular Github release.

**Comment by derritter88** [comment]
After installing this artifact build I can see the already created folders within Explorer but any kind of copy job does not work due to "not found", "cannot create" or similar exceptions.

**Comment by derritter88** [comment]
I can copy some files over via Explorer but after some times it also tells me that F:\ is no longer available.

**Comment by derritter88** [comment]
I went back, uninstall the artifact build, undone the bcdedit test mode and did a clean reinstallation of the latest rc5 build (also due to issues with running programs complaining about Windows test mode).

I have the same issue there: I can copy files but after some time I get the message "The path is not available."

Not sure if this is information is vital or not but I am using ZFS encryption for my subsets.

**Comment by derritter88** [comment]
I was able to identify a file name which breaks the copy process `IngvildØstberg.jpg`

**Comment by derritter88** [comment]
The interessting stuff is creating a folder or a file with special characters is possible - only copying existing files is not working.

**Comment by derritter88** [comment]
Interessting fact: After creating the pool on my Proxmox server Windows is showing the right folder structure:

```
PS E:\Users\mmuehlbacher\Downloads> ls F:


    Verzeichnis: F:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l        06.11.2023     07:36                Backup


PS E:\Users\mmuehlbacher\Downloads> ls F:\Backup\


    Verzeichnis: F:\Backup


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l        06.11.2023     07:36                Filme
d----l        06.11.2023     07:36                Serien
```

Not sure if this useful but this would be the ZFS version on Proxmox:
```
root@proxmox2:~# zfs version
zfs-2.1.13-pve1
zfs-kmod-2.1.13-pve1
```

**Comment by derritter88** [comment]
But after deleting some files Windows is no longer able to "see" the folder:

```
PS E:\Users\mmuehlbacher\Downloads> ls F:\Backup\Serien\
ls : Der Pfad "F:\Backup\Serien\" kann nicht gefunden werden, da er nicht vorhanden ist. (= the path "F:\Backup\xxx" cannot be found as it does not exist.)
In Zeile:1 Zeichen:1
+ ls F:\Backup\Serien\
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F:\Backup\Serien\:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Comment by derritter88** [comment]
Setting `zfs set driveletter=on` for the Backup/Serien dataset seems to help.

**Comment by derritter88** [comment]
Before I set driveletter to on I tried to unmount and mount the X20/Backup/Serien subset.
Instead of showing the right folder hierarchy it showed "Serien" directly at F:

**Comment by derritter88** [comment]
With driveletter=on I was also able to copy over the `IngvildØstberg.jpg` file.

I guess the logic with the symbolic links when driverletter is not being used causes those troubles.

**Comment by derritter88** [comment]
But it still keeps crashing the system when copying files to the ZFS subset even on a dedicated drive letter.

**Comment by derritter88** [comment]
@lundman Should I create a dedicated ticket for that and close this one or do you want to release a RC6 version and I test it again?

**Comment by lundman** [comment]
No need to make tickets for rc5 at the moment, fixed so many things.

**Comment by derritter88** [comment]
Okay - I'll stick to the release channel and have a look as soon as you release something new.

**Comment by derritter88** [comment]
Installed rc6 today (many thanks for this!!).
Windows still not honoring file structure.

ZFS subsets are encrypted and I need to decrypt them via `zfs load-key -r X20/Backup`
```
PS E:\Users\mmuehlbacher\Downloads> zfs load-key -r X20/Backup
Enter passphrase for 'X20/Backup':
1 / 1 key(s) successfully loaded
```

After that they are still unmounted 
```
PS E:\Users\mmuehlbacher\Downloads> zfs get mounted
NAME                        PROPERTY  VALUE    SOURCE
X20                         mounted   yes      -
X20@20231105                mounted   -        -
X20/Backup                  mounted   no       -
X20/Backup@20231105         mounted   -        -
X20/Backup/Filme            mounted   no       -
X20/Backup/Filme@20231105   mounted   -        -
X20/Backup/Serien           mounted   no       -
X20/Backup/Serien@20231106  mounted   -        -
```

I mount them one after the other
```
PS E:\Users\mmuehlbacher\Downloads> zfs mount X20/Backup/Filme
PS E:\Users\mmuehlbacher\Downloads> zfs mount X20/Backup/Serien
```

F:\ is still empty.

**Comment by lundman** [comment]
OK, so, if the pool is on E:, why are you expecting F: to have something?

You issue `zfs mount X20/Backup/Filme` but you didn't mount `zfs mount X20/Backup` first? It really should give you an error here, I will have to fix that.

**Comment by derritter88** [comment]
E:\was just the drive where Powershell opened (it's a build-in drive running NTFS).

When copying stuff via `driveletter=off` which should show the regular folder structure I still do get copy errors with rc6.
When setting `driveletter=on` and having a dedicated drive per ZFS subset it is working without any problem.

**Comment by lundman** [comment]
`driveletter=off` of everything, including pool's root dataset, would put in C: - which does have issues. Windows traversing from NTFS to another FS is tricky, so don't know if that works.

But presumably you meant `driveletter=off` on just the lower dataset, even with Backup mounted first, you see issues?

**Comment by derritter88** [comment]
This would be me current setup regarding driveletter:

```
X20                         driveletter  -            default
X20@20231105                driveletter  -            -
X20/Backup                  driveletter  -            default
X20/Backup@20231105         driveletter  -            -
X20/Backup/Filme            driveletter  on           local
X20/Backup/Filme@20231105   driveletter  -            -
X20/Backup/Filme@20231108   driveletter  -            -
X20/Backup/Serien           driveletter  on           local
X20/Backup/Serien@20231106  driveletter  -            -
```

On Windows I get 
![grafik](https://github.com/openzfsonwindows/openzfs/assets/8606313/d695a1d1-88f0-49da-b795-453e52fc0ed1)

which works.


Regarding the thing with the filesystem.
I have another drive which is being encrypted via Veracrypt and uses Winbtrfs.
With this I do get the information that filesystem = btrfs.

**Comment by lundman** [comment]
`filesystem = btrfs` yeah but where? we lie we are NTFS since so many things check, which will eventually be tied to the mimic property.  winbtrfs does as well, but it has a list of processnames to lie to.

**Comment by derritter88** [comment]
Regarding filesystem: It's totally fine for me if Windows things it has NTFS mounted.

**Comment by jonhermansen** [comment]
> `driveletter=off` of everything, including pool's root dataset, would put in C: - which does have issues. Windows traversing from NTFS to another FS is tricky, so don't know if that works.
> 
> But presumably you meant `driveletter=off` on just the lower dataset, even with Backup mounted first, you see issues?

@lundman Apologies for piling onto this issue, but I am trying to move my Windows home directory over to ZFS, and while it is possible to switch the drive letter via registry edits, I was hoping to keep everything mounted within `C:\`

Can you elaborate on what the issues are with mounting a dataset into `C:\`?

Will ZFS on Windows store SID ownership of the mountpoint? So far I've tried to create a file system at /Users/user, and /Users/user/Downloads. In the first case I can no longer log in as `user`, in the second case, Firefox complains about the Downloads folder being unwritable.

**Comment by lundman** [comment]
It is somewhat untested. I know for example if C: is case insensitive, as it usually is, and you mount ZFS on C:/pool, which might be case sensitive instead, the Windows kernel does not handle the difference "on the fly". I believe there is extra code around to handle that specific case (fish out the original case of the query) but it is not yet in the code.
The other option is to make sure ZFS has the same settings as C: - ie, case insensitive.

After that, I have only ever checked it does mount it in C, if asked to. I have not tested much else. So congratulations, you are now ahead! If you find it works inconsistently, file a bug report and we will take a crack at fixing them.

**Comment by lundman** [comment]
Ohman, that took a while but win11 dev VM is up and running, and first test has:

<img width="1222" alt="Screenshot 2024-01-12 at 16 52 29 (2)" src="https://github.com/openzfsonwindows/openzfs/assets/637168/07db570e-56ac-4e9c-a5a5-53ef84dc3bb7">

So I have something to work with!

**Comment by lundman** [comment]
OK so it does want to mount `BOOM/games/funones` on `/BOOM/games/funones`, so then it tries to find if there are any drive letters, so it gets parent name `BOOM/games` - checks where it is mounted, and gets `E:/BOOM/games` which appears to be the first mistake, that should just `E:/games`, no BOOM in there.

**Comment by lundman** [comment]
f85bf35

**Comment by derritter88** [comment]
This works now (from my initial tests) but when getting the space it looks a bit weird:

```
PS E:\Users\mmuehlbacher\Downloads> zfs get space
NAME             PROPERTY              VALUE            SOURCE
Backup-Data2     name                  Backup-Data2     -
Backup-Data2     available             2.59T            -
Backup-Data2     used                  949G             -
Backup-Data2     usedbysnapshots       0B               -
Backup-Data2     usedbydataset         128K             -
Backup-Data2     usedbyrefreservation  0B               -
Backup-Data2     usedbychildren        949G             -
Backup-Data2/VM  name                  Backup-Data2/VM  -
Backup-Data2/VM  available             2.59T            -
Backup-Data2/VM  used                  432G             -
Backup-Data2/VM  usedbysnapshots       0B               -
Backup-Data2/VM  usedbydataset         432G             -
Backup-Data2/VM  usedbyrefreservation  0B               -
Backup-Data2/VM  usedbychildren        0B               -
```

Not sure how the "root" (Backup-Data2) does count the space but it doubles it more or less.
Backuup-Data2/VM is a ZFS-native encrypted dataset.

**Comment by derritter88** [comment]
Additional info:

```
PS E:\Users\mmuehlbacher\Downloads> zfs list -t snapshot
no datasets available
```

**Comment by derritter88** [comment]
I guess due to the mentioned space problems FreeFileSync is unable to sync some data due to insufficient space:

```
17:01:44	Warning	Cannot determine free disk space for "F:\Data\HKS-Projekt".
		ERROR_INVALID_FUNCTION: Unzulässige Funktion. [GetDiskFreeSpaceEx]
17:01:48	Error	Cannot create directory "F:\Data\HKS-Projekt\Bilder\Segeln_FB2-Prüfungstörn_2019-05".
		ERROR_PATH_NOT_FOUND: Das System kann den angegebenen Pfad nicht finden. [CreateDirectory]
17:01:58	Error	Cannot open file "F:\Data\HKS-Projekt\sync.ffs_db".
		ERROR_FILE_NOT_FOUND: Das System kann die angegebene Datei nicht finden. [CreateFile]
		Cannot read file attributes of "F:\Data\HKS-Projekt\sync.ffs_db".
		Cannot open directory "F:\Data\HKS-Projekt".
		ERROR_PATH_NOT_FOUND: Das System kann den angegebenen Pfad nicht finden. [FindFirstFileEx]
17:01:58	Error	Stopped
```

**Comment by derritter88** [comment]
When copying via `driveletter=on` it works without any free-space-problems

**Comment by lundman** [comment]
Actually yeah, that is something we should keep an eye on, and excellent way to know if a reparse-point is working, or not.

If you have
```
E:     E:/games     E:/games/scifi
```
and you copy 1M into `E:/games/scifi` but the used space increases for `E:`, then the reparse point is not working, and `"/games/scifi"` is effectively just a directory under `E:`, and not a different mount.

Is this what you are seeing?

**Comment by derritter88** [comment]
I created another ZFS pool with a drive and copied over a ~50 MB file - following output I do get:

```
Backup-Data3                   name                  Backup-Data3                   -
Backup-Data3                   available             7.14T                          -
Backup-Data3                   used                  49.3M                          -
Backup-Data3                   usedbysnapshots       0B                             -
Backup-Data3                   usedbydataset         136K                           -
Backup-Data3                   usedbyrefreservation  0B                             -
Backup-Data3                   usedbychildren        49.2M                          -
Backup-Data3/Data              name                  Backup-Data3/Data              -
Backup-Data3/Data              available             7.14T                          -
Backup-Data3/Data              used                  48.7M                          -
Backup-Data3/Data              usedbysnapshots       0B                             -
Backup-Data3/Data              usedbydataset         48.7M                          -
Backup-Data3/Data              usedbyrefreservation  0B                             -
Backup-Data3/Data              usedbychildren        0B
```

**Comment by lundman** [comment]
Certainly looks like you copied it into Backup-Data3/Data

**Comment by derritter88** [comment]
I think so too - for the issue I had yesterday I will also check my 2nd drive again.
My current backup job works so far.

**Comment by derritter88** [comment]
Another issue:
When using `driveletter=off` then no special characters like french ones are working.

I get a "file not found" exception.

When using `driveletter=on` it works

**Comment by lundman** [comment]
`driveletter=off` for the pool or lower dataset? If it is in C: mount, its most likely crossing over that.

**Comment by derritter88** [comment]
> `driveletter=off` for the pool or lower dataset? If it is in C: mount, its most likely crossing over that.

Just for the lower dataset so it is mounted at a "root drive letter" - F: in my case

**Comment by lundman** [comment]
Yeah there many issues crossing C: -> C:/pool  - i have notes for handling it (more) but I have not yet got to it. Most people I think will expect a new drive letter for a separate storage

**Comment by derritter88** [comment]
In general it worked yesterday.
My pool has two subsets -> data & VMs and both of them are being shown correctly within the Explorer.

Only the copying data to F:\Data with special characters did not work as expected.

**Comment by derritter88** [comment]
Not sure if we are talking about the same - let me be more precise:

If I mount a pool it will get a dedicated driveletter.
```
PS E:\Users\mmuehlbacher\Downloads> zfs list
NAME                USED  AVAIL  REFER  MOUNTPOINT
Backup-Data3       3.38T  3.76T   132K  /Backup-Data3
Backup-Data3/Data  2.08T  3.76T  2.08T  /Backup-Data3/Data
Backup-Data3/VM    1.29T  3.76T  1.29T  /Backup-Data3/VM
```

In this case Backup-Data3 will be mounted as F: with Data & VM as folders:
```
PS F:\> ls


    Verzeichnis: F:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l        02.02.2024     07:13                VM
d----l        02.02.2024     07:13                Data
```

With this setup I do have issues with special characters, Umlauts and so on.


If I would do `zfs set driveletter=on Backup-Data3/Data` then this subeset would get it's own dedicated drive letter (e.g. G:)
There I do not have any issues with sepcial characters.

**Comment by lundman** [comment]
OK, so pool has driveletter on, and we are talking about lower datasets having driveletter off (reparse point mount) or on (driveletter mounted).

I can't imagine this goes wrong, so I look forward to trying it out and debugging what happens. Should probably make a separate issue for that problem

I pushed a -5-.exe today.

**Comment by derritter88** [comment]
I just compared both modes: If I want to open a photo from `F:\Data\Mathias\Pictures\Mathias\Wandern\28.11.2010 - Schöpfl` Windows would mention `xxxx.jpg probably file has moved or renamed`.

If on a dedicatd driveletter for the dedicated dataset it works.
