### ISSUE TITLE
zpool create does not work with \\.\ prefixed physical drives

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#329]
We should either document this better, give a better error message or ideally work with prefixed drive paths too.

See #294 and #325

**Comment by EchterAgo** [comment]
Closing because https://github.com/openzfsonwindows/openzfs/issues/325#issuecomment-1804625466

**Comment by sskras** [comment]
> Closing because [#325 (comment)](https://github.com/openzfsonwindows/openzfs/issues/325#issuecomment-1804625466)

I fail to relate that comment to this issue. Would you explain this?

**Comment by EchterAgo** [comment]
I thought the issue was the `\\.\` but it seems it is not. Also we can just keep #325 instead of having another open issue.
