### ISSUE TITLE
ZFS not enough space

### ISSUE THREAD

**Issue by derritter88** [openzfsonwindows/openzfs#332]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Win11 23H2
Architecture	| amd64
OpenZFS Version	| 2.2.0 rc6

### Describe the problem you're observing
When backing up music (~ 0,5 TB) files I get the information that there is not enough space on my ZFS pool:

```
PS E:\Users\mmuehlbacher\Downloads> zfs get space
NAME           PROPERTY              VALUE          SOURCE
Backup-1       name                  Backup-1       -
Backup-1       available             2.97T          -
Backup-1       used                  555G           -
Backup-1       usedbysnapshots       0B             -
Backup-1       usedbydataset         26.5K          -
Backup-1       usedbyrefreservation  0B             -
Backup-1       usedbychildren        555G           -
Backup-1/Data  name                  Backup-1/Data  -
Backup-1/Data  available             2.97T          -
Backup-1/Data  used                  555G           -
Backup-1/Data  usedbysnapshots       0B             -
Backup-1/Data  usedbydataset         555G           -
Backup-1/Data  usedbyrefreservation  0B             -
Backup-1/Data  usedbychildren        0B             -
```

Error message:
![grafik](https://github.com/openzfsonwindows/openzfs/assets/8606313/6d1ea380-2aeb-4db8-b103-e544ae3f767a)

If I ignore this error and start copying files it instantly BSOD with OpenZFS.sys

Other backups with equal or higher sizes work without any issue.
Also the regular Windows Explorer shows that I have plenty of free space.

**Comment by EchterAgo** [comment]
Likely the same as https://github.com/openzfsonwindows/openzfs/issues/271#issuecomment-1740166687

**Comment by derritter88** [comment]
@EchterAgo Thanks.
I'll close this ticket and follow #271
