### ISSUE TITLE
BSOD when trying to edit registry variables - 2.2.3-RC1

### ISSUE THREAD

**Issue by JayanWarden** [openzfsonwindows/openzfs#363]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 11 Pro
Distribution Version	| 23H2
Kernel Version	| 22631.3296
Architecture	| x64
OpenZFS Version	| zfswin-2.2.3rc1 + zfs-kmod-zfswin-2.2.3rc1

### Describe the problem you're observing

I was experiencing a total filesystem hang during heavy write load.
Zpool is a single SSD (Samsung 870 QVO) for testing ZFS.
Load was a Steam Game install at gigabit speeds, though the IO Speed was capped by CPU power (Testing zstd-19 compression on my system right now.)
Volume was able to be read (even file contents), but writing was impossible.
For example, trying to create a new text document on the volume with Windows Explorer caused the Explorer to stop responding and crash.

I wanted to reduce the number of IO Workers by editing zio_taskq_batch_pct from 90 to 60 because I thought maybe that was the culprit for the filesystem hang, the System was too busy.
System bluescreened as soon as I hit enter to save the new value.
BugCheck Code 0x1000007e caused by ntoskrnl.exe+35367c
I appended the MiniDump from the BSOD.
[031724-18093-01.dmp](https://github.com/openzfsonwindows/openzfs/files/14627334/031724-18093-01.dmp)

However, the filesystem hang is another problem, maybe related?

### Describe how to reproduce the problem

- Install 2.2.3-RC1 (upgraded from 2.2.2-RC13)
- Regedit any ZFS variable

**Comment by lundman** [comment]
so it is the regedit code - i thought it unlikely as there has been no changes. thanks

**Comment by lundman** [comment]
OK, turns out it was `gcm_impl`, in that it calls `can_use_avx()` which calls `__cpuid()` that ruined some registers. Corrected with ad3d9f7 and I rolled over to rc2 to avoid confusion.

**Comment by JayanWarden** [comment]
I can confirm RC2 lets me edit Registry without kernel panic. Thanks!

However before this, during further tests of RC1, I encountered another BSOD during heavy write load.
Should I open a new Issue for this?

SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
0x1000007e Caused by OpenZFS.sys+54de92
Parameters ffffffff`80000003 fffff803`964d0840 fffff001`61aeee38 fffff001`61aee650
[031824-16859-01.dmp](https://github.com/openzfsonwindows/openzfs/files/14637906/031824-16859-01.dmp)
