### ISSUE TITLE
ZFS load-key skips

### ISSUE THREAD

**Issue by derritter88** [openzfsonwindows/openzfs#368]
### System information
OpenZFS Version	|  2.2.3rc2-3-g0e4c16e0a6

### Describe the problem you're observing
If I want to decrypt my pool/s via `zfs load-key -r -a` the password line pops up and goes away without allowing/waiting to insert the password.
There is no possibility to add the decryption password

**Comment by derritter88** [comment]
After rolling back to `zfs-2.2.99-13-gfddfb6aeb5` the load-key command works again.

**Comment by lanato** [comment]
Confirming this issue. Directly passing a passphrase through `zfs mount -l` fails too. Running the command in bash instead of cmd indicates a segfault occurs before a password can be entered.
Last working build appears to be `2.2.99-15-gf9fd6397e6-dirty`

**Comment by lundman** [comment]
Thanks for reporting it

**Comment by lundman** [comment]
OK yeah, it's libfetch

`Exception thrown at 0x0000000000000000 in zfs.exe: 0xC0000005: Access violation executing location 0x0000000000000000.`

**Comment by lundman** [comment]
e102fe4

**Comment by derritter88** [comment]
Thanks - as always you have solved this and done an outstanding job!

Btw I have managed to restore ~30 TB of backups from your ZFS on Windows implementation to my server without any issues.
Thanks for that too!
