### ISSUE TITLE
compatibility option during pool creating could not read/parse file

### ISSUE THREAD

**Issue by v1ckxy** [openzfsonwindows/openzfs#372]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 11 23H2
Distribution Version	| Pro for Workstations
Kernel Version	| 22631.3447
Architecture	| x64
OpenZFS Version	| zfswin-2.2.3rc3, zfs-kmod-zfswin-2.2.3rc3

### Describe the problem you're observing
zpool create is unable to load a compatibility file
I tried to:
- Manually set the absolute path to the file:
"C:\Program Files\OpenZFS On Windows\OPENZFS_2.1_FREEBSD"), 
- Accessing first the path then trying to load using a relative path:
both ".\OPENZFS_2.1_FREEBSD" and "./OPENZFS_2.1_FREEBSD" are not working
- Without path at all:
"OPENZFS_2.1_FREEBSD"

File is called "OPENZFS_2.1_FREEBSD"

### Describe how to reproduce the problem
Copy compatibility files from freebsd 13.3 iso (FreeBSD-13.3-RELEASE-amd64-disc1.iso, inside usr/share/zfs/compatibility.d) to "OpenZFS on Windows" path.

Try to use it during pool creation:

 zpool.exe create -o compatibility=OPENZFS_2.1_FREEBSD [...]
throws the error:
Error: could not read/parse feature file(s): OPENZFS_2.1_FREEBSD

### Include any warning/errors/backtraces from the system logs

```
PS C:\Program Files\OpenZFS On Windows> zpool.exe create -O casesensitivity=insensitive -O normalization=formD -O compression=lz4 -O atime=off -o ashift=12 `
>> -o compatibility=OPENZFS_2.1_FREEBSD `
>> poolname raidz2 PHYSICALDRIVE5 PHYSICALDRIVE6 PHYSICALDRIVE9 PHYSICALDRIVE10 PHYSICALDRIVE11 PHYSICALDRIVE12
Expanded path to '\\?\PHYSICALDRIVE5'
Expanded path to '\\?\PHYSICALDRIVE6'
Expanded path to '\\?\PHYSICALDRIVE9'
Expanded path to '\\?\PHYSICALDRIVE10'
Expanded path to '\\?\PHYSICALDRIVE11'
Expanded path to '\\?\PHYSICALDRIVE12'
working on dev [...]
setting path here '/dev/physicaldrive5'
[...]
Error: could not read/parse feature file(s): OPENZFS_2.1_FREEBSD
poolname 
PS C:\Program Files\OpenZFS On Windows>
```

**Comment by v1ckxy** [comment]
Tried with zfsonlinux compatibility files too:
https://salsa.debian.org/zfsonlinux-team/zfs/-/tree/master/cmd/zpool/compatibility.d

and... they don't work either.

**Comment by lundman** [comment]
Ah ok, I have never checked if they work, but should probably include them in the installer and fix path, as well as the bug

**Comment by lundman** [comment]
4b326b9

Updated paths to work for us, be pretty hard to use the Unix default. Confirmed it read the file in successfully.

**Comment by v1ckxy** [comment]
Just saw the commit. Thankyou very much!

**Comment by lundman** [comment]
Posted `OpenZFSOnWindows-debug-.99-137-g4b326b9b92-dirty.exe` to test an unrelated fix, which includes the compat commit.

**Comment by v1ckxy** [comment]
Updating openzfs was hellish (a lot of bsds; had to manually delete the driver from system32/drivers, and uninstall drivers using "pnputil.exe -d drivername.inf"), however...

![image](https://github.com/openzfsonwindows/openzfs/assets/43522971/ee93278e-1181-4f0e-a2e8-8df31d572fd3)

![image](https://github.com/openzfsonwindows/openzfs/assets/43522971/9973916e-617e-47ad-8541-deac29e90d74)

Looks like this option now it's working without issues. 

I think we can close this :)

However, "zpool export" hangs during the export and I'm not sure if it's because of the compatibility options set or something else; I will open another issue and try to replicate it using another pool (I cannot destroy this one)

Have a good one,
Regards

**Comment by lundman** [comment]
heard several report on uninstalling bsods, maybe i should look into that

**Comment by v1ckxy** [comment]
While checking the registry the other day to cleanup things, I saw that windows had two device drivers "attached" to the same root (OpenZFS Controller), so it looks like it didn't uninstalled the first one properly.

// Sorry about the offtopic
