### ISSUE TITLE
Wrong ENV PATH on install

### ISSUE THREAD

**Issue by Mirkic7** [openzfsonwindows/openzfs#383]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 11 23H2
Distribution Version	| Pro
Kernel Version	| OS Build 22631.3593
Architecture	| x64
OpenZFS Version	|  2.2.3rc5

### Describe the problem you're observing

After installation 'zfs' or 'zpool' commands are not in PATH.
Checking ENV variables in System variables, it shows PATH for ZFS is added as: ;C:\Program Files\OpenZFS On Windows; - with semicolons in front and back.
Removing them manually fixes PATH issue.

### Describe how to reproduce the problem

Fresh install of ZFS on Windows 2.2.3rc5

### Include any warning/errors/backtraces from the system logs

![Screenshot 2024-05-28 112823](https://github.com/openzfsonwindows/openzfs/assets/6661512/c731306a-35dd-40bc-ad15-64c6a7525edb)

**Comment by lundman** [comment]
Hmm I just use Inno-setup snippets for it

https://github.com/openzfsonwindows/openzfs/blob/development/contrib/windows/Inno.Setup/environment.iss#L5-L23

**Comment by sskras** [comment]
> ### Describe the problem you're observing
> After installation 'zfs' or 'zpool' commands are not in PATH. Checking ENV variables in System variables, it shows PATH for ZFS is added as: ;C:\Program Files\OpenZFS On Windows; - with semicolons in front and back. Removing them manually fixes PATH issue.
> 
> ### Describe how to reproduce the problem
> Fresh install of ZFS on Windows 2.2.3rc5

Can you please open CMD console and run this command:
```cmd
echo %PATH%
```

At least zfswin-2.2.3rc4 it works on my laptop just fine:

![image](https://github.com/openzfsonwindows/openzfs/assets/7887758/63d0644e-53a4-4899-aaae-161bf0f035fb)

**Comment by Mirkic7** [comment]
Hi,

checked PATH as you mentioned, and this is result (reinstalled from scratch).
What is 'extra' there is an double quotation mark, which should not be there.

![image](https://github.com/openzfsonwindows/openzfs/assets/6661512/c83a7ca5-bcba-468d-94d5-9fb19dfd1d06)

**Comment by lundman** [comment]
Since we add ` Paths := Paths + ';'+ Path +';'` and the `"` comes before `;` that suggests it was there before we added ZFS ?

**Comment by Mirkic7** [comment]
Indeed, you are right.
I rolled back snapshot, and it was there previously.

False flag, can be closed.

**Comment by lundman** [comment]
phew! Thanks.
