### ISSUE TITLE
Installation of OpenZFSOnWindows-debug-.99-149-gf9ec771f74.exe fails 

### ISSUE THREAD

**Issue by florean** [openzfsonwindows/openzfs#386]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Windows 11 Pro
Distribution Version	|  23H2
Kernel Version	| 22631.3737
Architecture	| AMD64
OpenZFS Version	|  OpenZFSOnWindows-debug-.99-149-gf9ec771f74

### Describe the problem you're observing
Installation fails with an error dialog box and an "EnumQueryServicesStatus:OpenService FAILED 1060:" message.
I previously had a working installation on an older build.  After running the installer, I saw the error message but didn't receive the error dialog and the installation appeared to finish, prompting me to reboot my system.  However, after rebooting ZFS threw an error, so I completely uninstalled and reinstalled.  After uninstalling, the installation will no longer complete.

### Describe how to reproduce the problem
Download the OpenZFSOnWindows-debug-.99-149-gf9ec771f74.exe and click on install.

### Include any warning/errors/backtraces from the system logs

```
C:\Program Files\OpenZFS On Windows>zfsinstaller uninstall OpenZFS.inf
Unable to open ZFS devnode, already uninstalled?
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.



DefaultUninstall 128 OpenZFS.inf
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

uninstallRootDevice:
uninstallRootDevice: looking for device rootnode to remove...
uninstallRootDevice: device found, removing ...
uninstallRootDevice: device found, removing ...
uninstallRootDevice: exit 0:0x0

C:\Program Files\OpenZFS On Windows>zfsinstaller install OpenZFS.inf
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.



OpenZFS_Install 128 OpenZFS.inf
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

StartServiceA failed, error 1058
installRootDevice: exit 0:0x0

C:\Program Files\OpenZFS On Windows
```

**Comment by florean** [comment]
Okay, I went into Device Manager and there were four "OpenZFS controller" devices under "Storage volumes".  After removing them, I rebooted and was able to successfully install.

**Comment by sskras** [comment]
I'd say it's not fixed if (1) you needed some manual intervention (cleanup).

Then (2) the installer should report the blockers it encounters in a friendly manner.

**Comment by lundman** [comment]
It's hard to know if they were there from earlier, and the new "fixed" installer noticed it and skipped. Either way, a nicer error would definitely be in order. I don't really like the service prints either, it was mostly there for debugging when zfsinstaller was made - so it could use some TLC.
