### ISSUE TITLE
Adding EV certificate

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/openzfs#40]
Having obtained an EV certificate, from SSL.com, and eSigner.com, I'm looking for the best way to use it.

It would seem they have a `CodeSignTool.bat` which is a bit poor. But I certainly could change CMake to call it.

I've yet to figure out the "Windows Hardware Developer Program" register, it broke completely trying to register a new account.

**Comment by lundman** [comment]
OK so need to go through whole company registration procedure yet again, this time for partner.microsoft. Which seems to including everything I had to do for the EV certificate again, how tedious.

**Comment by lundman** [comment]
I have received my yubikey.

It asks for the PIN every single time it signs something, so something like 16 times to compile the project. This clearly is no acceptable. Need to find some way to cache the authentication, or, from PIV entirely.

When compiling over RDP, instead of asking for PIN, it just asks for "smart card" to be inserted.

**Comment by sskras** [comment]
Per this tweet: https://twitter.com/openzfsonwindow/status/1471321209300471809
... can this issue be related and fixed already?

**Comment by lundman** [comment]
I do believe the latest nightly is properly codesigned now.
