### ISSUE TITLE
`zfswin-2.2.3rc6` tag is missing

### ISSUE THREAD

**Issue by sskras** [openzfsonwindows/openzfs#405]
Currently my copy of the repo contains only tags up to `2.2.3rc5`:
```sh
saukrs@omn:~/debug/src/github.com/openzfsonwindows/openzfs$ git tag | grep 2.2.3
zfswin-2.2.3rc1
zfswin-2.2.3rc2
zfswin-2.2.3rc3
zfswin-2.2.3rc4
zfswin-2.2.3rc5
```

The `rc6` tag could help bisecting regression like #404 (avoid search for a specific commit IDs).

Is it possible to add the tag, so developers can fetch it easily?

**Comment by sskras** [comment]
PS. I meant testers. Because the are very little of the real developers in this project :)

**Comment by sskras** [comment]
Well, `2.2.6rc2` is also missing:
```sh
$ git tag | grep 2.2.6
zfswin-2.2.6rc1
zfswin-2.2.6rc3
zfswin-2.2.6rc4
zfswin-2.2.6rc5
zfswin-2.2.6rc6
zfswin-2.2.6rc7
```

This is not a request to rewrite commit history, no. Assigning the tag to a commit hopefully should be enough, eg:
```sh
$ git tag zfswin-2.2.6rc2 4b429b48f20e6a47a18becab64484ce5ff1ef45c
```

**Comment by lundman** [comment]
I pushed my local repo on 2.2.3. As for 2.2.6rc2, I deliberately skipped rc2 due to a quick ad-hoc fix for someone to test, so went to rc3 to avoid binary two "rc2"s existing. I can create the tag if you need, it would be somewhat arbitrary

**Comment by sskras** [comment]
Thanks for the `2.2.3rc6` tag.

Re `2.2.6rc2`: OK, if it's minor, I would probably keep that in mind and just skip it (should I do a regression testing:)
