### ISSUE TITLE
zpool I/O errors after windows is put to lock for about 1 hour

### ISSUE THREAD

**Issue by himugo** [openzfsonwindows/openzfs#425]
### System information

Windows 11 Pro | Build 26100
 --- | ---
Windows 11	|
Build 26100	|
Windows	|
OpenZFS Version
zfs-2.1.99-3126-g97bdecb6f
zfs-kmod-zfs-2.1.99-3126-g97bdecb6f	|

### Describe the problem you're observing

Whenever I lock my windows and leave it for about an hour, after logging in the zpool is suspended and I see I/O errors in zpool status

I am using a Pi+ PCIe Riser for using a LSI SAS 2008 Falcon Card

### Describe how to reproduce the problem

Start PC
Let the zpool be imported
After about 30 40 minutes of using the computer lock windows using Start+L
Leave for 1 hour
Log In
Check zpool status in cmd

If there's any previous issue that is similar to this, let me know.
Also any help is truely appreciated

**Comment by lundman** [comment]
Oh ah, I do not think I ever tried lock/login, so that could be very likely. Does PC sleep or hibernate, or just locked? Do your HDDs power down (assuming HDD).

**Comment by himugo** [comment]
@lundman Just Locked. I have also optimized for various power management settings like Fast Shutdown and other pci power management settings.
Regarding HDDs no they don't power off, because I am powering them using a seperate PSU.
I am still suspicious with windows and it's settings. 
Previously when I was running proxmox in this system, this never happened. (also the fact that with proxmox I never have to worry about locking my system)

**Comment by himugo** [comment]
@lundman quick update on my problem.

I just tinkered around and found out that the problem I was having with all the lock screen thing was that,
As soon as I lock my computer, my computer gets in an idle stage, making cpu usage low, and subsequently making power consumption low.
Whenever I log in to the system cpu fans speed up quickly making power consumption higher, which ultimately leads to small amounts of voltage fluctuations.
This voltage fluctuation leads to irresponsiveness of SAS Card, which is plugged in a Pi+ PCIe Extender, which causes I/O errors in zpool.

I think I can now close this issue.

**Comment by lundman** [comment]
Huh neat, thanks for letting me know. I still should check sleep/hibernate works - there is a whole area in ZFS about that
