### ISSUE TITLE
"zfs destroy <pool name>/<vol name>" command crashing

### ISSUE THREAD

**Issue by datacore-raj** [openzfsonwindows/openzfs#46]
**Zpool command** -> zpool create -o ashift=12 tank1 PHYSICALDRIVE1 PHYSICALDRIVE2
**Zvol command** -> zfs create -o sync=always -o volblocksize=128k -v 10g tank1/myvol

crash after following command
zfs destroy tank1/myvol

**Stack Trace** ->
kd> k
 # Child-SP          RetAddr           Call Site
00 ffffe08e`8f8aaf38 fffff802`4e2a4ab2 nt!DbgBreakPointWithStatus
01 ffffe08e`8f8aaf40 fffff802`4e2a4237 nt!KiBugCheckDebugBreak+0x12
02 ffffe08e`8f8aafa0 fffff802`4e1c76e7 nt!KeBugCheck2+0x957
03 ffffe08e`8f8ab6c0 fffff802`4e1df74f nt!KeBugCheckEx+0x107
04 ffffe08e`8f8ab700 fffff802`4e1a241f nt!PspSystemThreadStartup$filt$0+0x44
05 ffffe08e`8f8ab740 fffff802`4e1d00cf nt!_C_specific_handler+0x9f
06 ffffe08e`8f8ab7b0 fffff802`4e03ab20 nt!RtlpExecuteHandlerForException+0xf
07 ffffe08e`8f8ab7e0 fffff802`4e07fe74 nt!RtlDispatchException+0x430
08 ffffe08e`8f8abf30 fffff802`4e1d8e42 nt!KiDispatchException+0x144
09 ffffe08e`8f8ac5e0 fffff802`4e1d5168 nt!KiExceptionDispatch+0xc2
0a ffffe08e`8f8ac7c0 fffff802`5410d3a3 nt!KiPageFault+0x428
0b (Inline Function) --------`-------- OpenZFS!KeGetCurrentThread+0x9 [C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\wdm.h @ 121] 
0c (Inline Function) --------`-------- OpenZFS!PsGetCurrentThread+0x9 [C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\wdm.h @ 28181] 
0d ffffe08e`8f8ac950 fffff802`541e9624 OpenZFS!spl_mutex_enter+0x13 [C:\Users\rsoni\Desktop\openzfs\module\os\windows\spl\spl-mutex.c @ 115] 
0e ffffe08e`8f8ac9b0 fffff802`54155907 OpenZFS!dnode_rele+0x14 [C:\Users\rsoni\Desktop\openzfs\module\zfs\dnode.c @ 1597] 
0f ffffe08e`8f8ac9e0 fffff802`54155d7d OpenZFS!zvol_shutdown_zv+0x37 [C:\Users\rsoni\Desktop\openzfs\module\zfs\zvol.c @ 825] 
10 ffffe08e`8f8aca10 fffff802`54230903 OpenZFS!zvol_last_close+0xd [C:\Users\rsoni\Desktop\openzfs\module\zfs\zvol.c @ 972] 
11 ffffe08e`8f8aca40 fffff802`54156188 OpenZFS!zvol_os_detach_zv+0x43 [C:\Users\rsoni\Desktop\openzfs\module\os\windows\zfs\zvol_os.c @ 649] 
12 ffffe08e`8f8aca80 fffff802`541568dc OpenZFS!zvol_remove_minors_impl+0xa8 [C:\Users\rsoni\Desktop\openzfs\module\zfs\zvol.c @ 1233] 
13 ffffe08e`8f8acb10 fffff802`541033ba OpenZFS!zvol_task_cb+0x2c [C:\Users\rsoni\Desktop\openzfs\module\zfs\zvol.c @ 1476] 
14 ffffe08e`8f8acb40 fffff802`4e09abc5 OpenZFS!taskq_thread+0x21a [C:\Users\rsoni\Desktop\openzfs\module\os\windows\spl\spl-taskq.c @ 2095] 
15 ffffe08e`8f8acc10 fffff802`4e1cea3c nt!PspSystemThreadStartup+0x55
16 ffffe08e`8f8acc60 00000000`00000000 nt!KiStartSystemThread+0x1c

Additional details ->

FAULTING_SOURCE_LINE:  C:\Users\rsoni\Desktop\openzfs\module\os\windows\spl\spl-mutex.c

FAULTING_SOURCE_FILE:  C:\Users\rsoni\Desktop\openzfs\module\os\windows\spl\spl-mutex.c

FAULTING_SOURCE_LINE_NUMBER:  115

FAULTING_SOURCE_CODE:  
 ```
  111: {
   112: 	NTSTATUS Status;
   113: 	kthread_t *thisthread = current_thread();
   114: 
>  115: 	if (mp->m_initialised != MUTEX_INITIALISED)
   116: 		panic("%s: mutex not m_initialised\n", __func__);
   117: 
   118: 	if (mp->m_owner == thisthread)
   119: 		panic("mutex_enter: locking against myself!");
   120: 
```

**Comment by lundman** [comment]
Possibly `zv->zv_dn` is NULL, I'll take a look in the morning

**Comment by lundman** [comment]
e230b03
