### ISSUE TITLE
Bugcheck during zfs snapshot destroy

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#48]
commands to repro:-
------------------------------------
_zpool create -f testpool PHYSICALDRIVE1
zfs create -V 150m testpool/testvol
zfs snapshot testpool/testvol@testsnap
zfs destroy testpool/testvol@testsnap_

![image](https://user-images.githubusercontent.com/84957265/136367663-b7a539b2-f2b4-47c2-acdf-82a36b60232f.png)

**Comment by lundman** [comment]
Heh yeah, lua is not called at all, so something went quite wrong there. The last valid call is `dsl_destroy_snapshots_nvl`.
Wonder if the nvl is garbage - it uses function ptrs.

**Comment by lundman** [comment]
2aaedbf missed one, so pushed 2e370ae64752cfbdc0d189ce3be220979b547435
did I miss more? There are a few that needs to be updated before we can use them, wrt to calling convention use of registers, ad non-volatile registers

**Comment by lundman** [comment]
It uses generic (C) versions of sha256/512 and aes.  This repo has never used the assembler versions, as assembler was only enabled in 2aaedbf .
