### ISSUE TITLE
zpool.exe create command displays "failed to create mount point" error

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#50]
zpool create command creates a directory with poolname.  If that directory already exists, then it reports the error.

_"cannot mount '/testpool': failed to create mountpoint: File exists"_

In Zfsin, the code which creates directory is excluded for windows. Can this be done for openzfs as well.

*
 * In windows, we do not create the directory, as it is made
 * when we create the reparse point.
 */
#ifndef _WIN32
		if (mkdirp(mountpoint, 0755) != 0) {
			zfs_error_aux(hdl, dgettext(TEXT_DOMAIN,
			    "failed to create mountpoint"));
			return (zfs_error_fmt(hdl, EZFS_MOUNTFAILED,
			    dgettext(TEXT_DOMAIN, "cannot mount '%s'"),
			    mountpoint));
		}
#endif
	}

**Comment by lundman** [comment]
~zpool~ zfs create?
