### ISSUE TITLE
Not able to create encrypted zpool with keyformat=passphrase

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#51]
Command to repro:

_zpool.exe create -O encryption=aes-256-gcm -O keyformat=passphrase mypool PhysicalDrive1_

Expanded path to '\\?\PhysicalDrive1'
working on dev '#1048576#4284481536#\\?\PhysicalDrive1'
setting path here '/dev/physicaldrive1'
setting physpath here '#1048576#4284481536#\\?\PhysicalDrive1'
Enter new passphrase:
Re-enter new passphrase:
**cannot create 'mypool': Failed to generate salt.**

**Comment by lundman** [comment]
4df76eb
