### ISSUE TITLE
Occasionally build fails due to WPP

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/openzfs#54]
Sometimes, making a small change and attempting to compile will fail with:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol WPP_CALL_spl_vnode_c532 referenced in function spl_vnode_fini	C:\src\openzfs\out\build\x64-Debug\openzfs	C:\src\openzfs\out\build\x64-Debug\splkern.lib(spl-vnode.c.obj)	1	
Error	LNK2019	unresolved external symbol WPP_CALL_spl_vnode_c1330 referenced in function vnode_drain_delayclose	C:\src\openzfs\out\build\x64-Debug\openzfs	C:\src\openzfs\out\build\x64-Debug\splkern.lib(spl-vnode.c.obj)	1	
Error	LNK2019	unresolved external symbol WPP_CALL_spl_vnode_c1356 referenced in function vnode_drain_delayclose	C:\src\openzfs\out\build\x64-Debug\openzfs	C:\src\openzfs\out\build\x64-Debug\splkern.lib(spl-vnode.c.obj)	1	
Error	LNK2019	unresolved external symbol WPP_CALL_spl_vnode_c1384 referenced in function vnode_drain_delayclose	C:\src\openzfs\out\build\x64-Debug\openzfs	C:\src\openzfs\out\build\x64-Debug\splkern.lib(spl-vnode.c.obj)	1	
Error	LNK2019	unresolved external symbol WPP_CALL_spl_vnode_c617 referenced in function getf	C:\src\openzfs\out\build\x64-Debug\openzfs	C:\src\openzfs\out\build\x64-Debug\splkern.lib(spl-vnode.c.obj)	1	
```

It is easy to work around, just "save" (refresh) any CMakelist.txt file for it to wipe the cache, to rebuild all. 

Sometimes you really just want to compile one file, so rebuild all is frustrating.

**Comment by datacore-rm** [comment]
WPP preprocessor generates the .tmh files and this is generated only during cache generation. The .tmh file contains the line number reference to the TraceEvent() calls in the .c files. Later when any .c file is modified and then build, it doesn't rebuild the corresponding .tmh file, resulting in the reference mismatch error. We shall look into how we can resolve this.

In the mean time, the WPP functionality can be disabled by commenting the wpp("${CMAKE_SOURCE_DIR}/out/build") calls in four CMakeLists.txt file.

**Comment by lundman** [comment]
I'm ok running without WPP, so it is no great priority.
