### ISSUE TITLE
bug check during zil replaying

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#58]
In zil_replaying(zilog_t *zilog,), the zilog pointer=NULL.

As per https://github.com/openzfs/zfs/commit/93e3658035030dedc4a25c25e8b410a549bafa74 ,

zvol_os_create_minor()
{
...
   zv->zv_zilog = zil_open(os, zvol_get_data); // this call is missing?
...
} 
-------------------------------------------------------------------------------------------------------------
27: kd> !analyze -v
SYSTEM_SERVICE_EXCEPTION (3b)
An exception happened while executing a system service routine.
Arguments:
Arg1: 00000000c0000005, Exception code that caused the bugcheck
Arg2: fffff809d0b511be, Address of the instruction which caused the bugcheck
Arg3: ffffc801d6a41630, Address of the context record for the exception that caused the bugcheck
Arg4: 0000000000000000, zero.

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 2

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on HULK

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 3

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 91

    Key  : Analysis.System
    Value: CreateObject

BUGCHECK_CODE:  3b

BUGCHECK_P1: c0000005

BUGCHECK_P2: fffff809d0b511be

BUGCHECK_P3: ffffc801d6a41630

BUGCHECK_P4: 0

CONTEXT:  ffffc801d6a41630 -- (.cxr 0xffffc801d6a41630)
rax=0000000000000001 rbx=ffffb78c19aeb0c0 rcx=0000000000000000
rdx=ffffb78c084f0dc0 rsi=0000000000000001 rdi=0000000000018000
rip=fffff809d0b511be rsp=ffffc801d6a42020 rbp=0000000000000000
 r8=0000000000000001  r9=0000000000000001 r10=000000005f9fc46c
r11=ffffb78c19b030c0 r12=0000000000000000 r13=0000000000000000
r14=ffffb78c0832a040 r15=ffffb78c09095340
iopl=0         nv up ei ng nz na pe nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010282
ZFSin!zil_replaying+0xe:
fffff809`d0b511be 80b91901000002  cmp     byte ptr [rcx+119h],2 ds:002b:00000000`00000119=??
Resetting default scope

PROCESS_NAME:  zpool.exe

STACK_TEXT:  
ffffc801`d6a42020 fffff809`d0adb658 : 00000000`00000000 ffffc801`d6a42340 00000000`000180c0 fffff809`d0b4138f : ZFSin!zil_replaying+0xe [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3639] 
ffffc801`d6a42070 fffff809`d0b51148 : 16e859b8`4d45796a 37e6ac8b`00aee00f 00000000`00000194 00000000`0000352c : ZFSin!zvol_replay_write+0xf8 [C:\test-build-branch\openzfs\module\zfs\zvol.c @ 529] 
ffffc801`d6a420e0 fffff809`d0b4e456 : 00000000`00000001 00000000`00000000 ffffb78c`08870278 fffff803`c64fdf9c : ZFSin!zil_replay_log_record+0x118 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3574] 
ffffc801`d6a42140 fffff809`d0b50fe8 : ad2ba415`78fb3253 ffffb78c`0ffe25a0 ffffb78c`08b5e340 ffffb78c`0ffe25a0 : ZFSin!zil_parse+0x286 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 411] 
ffffc801`d6a42310 fffff809`d0bbdeb7 : ffffe30d`dc132dd3 fffff809`d0ca2979 00000000`0000001f ffffb78c`001dbc10 : ZFSin!zil_replay+0xb8 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3629] 
ffffc801`d6a42390 fffff809`d0adc205 : fffff809`d20b8960 00000000`00000003 fffff809`d0d28000 fffff809`d0a8d5bd : ZFSin!zvol_os_create_minor+0x217 [C:\test-build-branch\openzfs\module\os\windows\zfs\zvol_os.c @ 750] 
ffffc801`d6a42410 fffff809`d0ac78ef : ffffe30d`dc132ac3 00000000`00000000 00000000`000075b8 ffffb78c`08f0002b : ZFSin!zvol_create_minors_recursive+0x105 [C:\test-build-branch\openzfs\module\zfs\zvol.c @ 1160] 
ffffc801`d6a42480 fffff809`d0aa39e6 : ffffb78c`00026040 fffff809`d0a8544d 00000000`00000000 fffff803`c64f0019 : ZFSin!spa_import+0x8ff [C:\test-build-branch\openzfs\module\zfs\spa.c @ 6277] 
ffffc801`d6a425b0 fffff809`d0a9bfef : 00000000`00000000 ffffb78b`40000010 0000001c`01180006 fffff809`d0a84e4c : ZFSin!zfs_ioc_pool_import+0x2a6 [C:\test-build-branch\openzfs\module\zfs\zfs_ioctl.c @ 1594] 
ffffc801`d6a42660 fffff809`d0bb6e04 : ffffc801`d6a42710 00000000`00000000 00000000`00000001 00000000`00000000 : ZFSin!zfsdev_ioctl_common+0x2ef [C:\test-build-branch\openzfs\module\zfs\zfs_ioctl.c @ 7785] 
ffffc801`d6a42700 fffff809`d0baab83 : ffff8fbf`fba7eac8 ffffbf84`90a75d00 00000000`00000000 ffffa80d`00000000 : ZFSin!zfsdev_ioctl+0xc4 [C:\test-build-branch\openzfs\module\os\windows\zfs\zfs_ioctl_os.c @ 791] 
ffffc801`d6a42780 fffff803`c68a40c0 : ffffbf84`91bebe70 ffffc801`d6a42b80 00000000`00000001 00000000`00000000 : ZFSin!dispatcher+0x103 [C:\test-build-branch\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 5502] 
ffffc801`d6a42820 fffff803`c68a345c : ffffbf84`00000000 ffffbf84`91bebe04 fffff780`000002dc ffffc801`d6a42b80 : nt!IopSynchronousServiceTail+0x1a0
ffffc801`d6a428e0 fffff803`c68a26b6 : ffffbf84`90a75d00 00000000`00000000 00000000`00000000 00000000`00000000 : nt!IopXxxControlFile+0xd9c
ffffc801`d6a42a20 fffff803`c6602e03 : ffff8fc7`e3e03788 ffff8fc7`e3f1f018 ffff8193`310bc6f7 00000000`00000000 : nt!NtDeviceIoControlFile+0x56
ffffc801`d6a42a90 00007ffa`7e2f5d54 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13
00000093`752fccf8 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ffa`7e2f5d54

FAULTING_SOURCE_LINE:  C:\test-build-branch\openzfs\module\zfs\zil.c

FAULTING_SOURCE_FILE:  C:\test-build-branch\openzfs\module\zfs\zil.c

FAULTING_SOURCE_LINE_NUMBER:  3639

SYMBOL_NAME:  ZFSin!zil_replaying+e

MODULE_NAME: ZFSin

IMAGE_NAME:  ZFSin.sys

STACK_COMMAND:  .cxr 0xffffc801d6a41630 ; kb

BUCKET_ID_FUNC_OFFSET:  e

FAILURE_BUCKET_ID:  0x3B_c0000005_ZFSin!zil_replaying

OS_VERSION:  10.0.14393.4467

BUILDLAB_STR:  rs1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {e17c20a8-44ab-4dab-70b8-b91b91f0bf5a}

Followup:     MachineOwner
---------

27: kd> k
 # Child-SP          RetAddr           Call Site
00 ffffc801`d6a40d48 fffff803`c6603329 nt!KeBugCheckEx
01 ffffc801`d6a40d50 fffff803`c660287c nt!KiBugCheckDispatch+0x69
02 ffffc801`d6a40e90 fffff803`c65fb6fd nt!KiSystemServiceHandler+0x7c
03 ffffc801`d6a40ed0 fffff803`c654a2b1 nt!RtlpExecuteHandlerForException+0xd
04 ffffc801`d6a40f00 fffff803`c65490d4 nt!RtlDispatchException+0x421
05 ffffc801`d6a41600 fffff803`c6603402 nt!KiDispatchException+0x1e4
06 ffffc801`d6a41cb0 fffff803`c6600446 nt!KiExceptionDispatch+0xc2
07 ffffc801`d6a41e90 fffff809`d0b511be nt!KiPageFault+0x406
08 ffffc801`d6a42020 fffff809`d0adb658 ZFSin!zil_replaying+0xe [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3639] 
09 ffffc801`d6a42070 fffff809`d0b51148 ZFSin!zvol_replay_write+0xf8 [C:\test-build-branch\openzfs\module\zfs\zvol.c @ 529] 
0a ffffc801`d6a420e0 fffff809`d0b4e456 ZFSin!zil_replay_log_record+0x118 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3574] 
0b ffffc801`d6a42140 fffff809`d0b50fe8 ZFSin!zil_parse+0x286 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 411] 
0c ffffc801`d6a42310 fffff809`d0bbdeb7 ZFSin!zil_replay+0xb8 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3629] 
0d ffffc801`d6a42390 fffff809`d0adc205 ZFSin!zvol_os_create_minor+0x217 [C:\test-build-branch\openzfs\module\os\windows\zfs\zvol_os.c @ 750] 
0e ffffc801`d6a42410 fffff809`d0ac78ef ZFSin!zvol_create_minors_recursive+0x105 [C:\test-build-branch\openzfs\module\zfs\zvol.c @ 1160] 
0f ffffc801`d6a42480 fffff809`d0aa39e6 ZFSin!spa_import+0x8ff [C:\test-build-branch\openzfs\module\zfs\spa.c @ 6277] 
10 ffffc801`d6a425b0 fffff809`d0a9bfef ZFSin!zfs_ioc_pool_import+0x2a6 [C:\test-build-branch\openzfs\module\zfs\zfs_ioctl.c @ 1594] 
11 ffffc801`d6a42660 fffff809`d0bb6e04 ZFSin!zfsdev_ioctl_common+0x2ef [C:\test-build-branch\openzfs\module\zfs\zfs_ioctl.c @ 7785] 
12 ffffc801`d6a42700 fffff809`d0baab83 ZFSin!zfsdev_ioctl+0xc4 [C:\test-build-branch\openzfs\module\os\windows\zfs\zfs_ioctl_os.c @ 791] 
13 ffffc801`d6a42780 fffff803`c68a40c0 ZFSin!dispatcher+0x103 [C:\test-build-branch\openzfs\module\os\windows\zfs\zfs_vnops_windows.c @ 5502] 
14 ffffc801`d6a42820 fffff803`c68a345c nt!IopSynchronousServiceTail+0x1a0
15 ffffc801`d6a428e0 fffff803`c68a26b6 nt!IopXxxControlFile+0xd9c
16 ffffc801`d6a42a20 fffff803`c6602e03 nt!NtDeviceIoControlFile+0x56
17 ffffc801`d6a42a90 00007ffa`7e2f5d54 nt!KiSystemServiceCopyEnd+0x13
18 00000093`752fccf8 00000000`00000000 0x00007ffa`7e2f5d54
27: kd> .frame 0n8;dv /t /v
08 ffffc801`d6a42020 fffff809`d0adb658 ZFSin!zil_replaying+0xe [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3639] 
@rcx              struct zilog * zilog = 0x00000000`00000000
@rdx              struct dmu_tx * tx = 0xffffb78c`084f0dc0
27: kd> .frame 0n9;dv /t /v
09 ffffc801`d6a42070 fffff809`d0b51148 ZFSin!zvol_replay_write+0xf8 [C:\test-build-branch\openzfs\module\zfs\zvol.c @ 529] 
@r14              void * arg1 = 0xffffb78c`0832a040
<unavailable>     void * arg2 = <value unavailable>
<unavailable>     <unnamed-tag> byteswap = <value unavailable>
@r14              struct zvol_state * zv = 0xffffb78c`0832a040
<unavailable>     struct lr_write_t * lr = <value unavailable>
@rbx              char * data = 0xffffb78c`19aeb0c0 "3???"
@r15              struct objset * os = 0xffffb78c`09095340
@r12              unsigned int64 offset = 0
@rdi              unsigned int64 length = 0x18000
@rsi              struct dmu_tx * tx = 0xffffb78c`084f0dc0
@ebp              int error = 0n0
27: kd> dx -id 0,0,ffffbf8490a75800 -r1 ((ZFSin!zvol_state *)0xffffb78c0832a040)
((ZFSin!zvol_state *)0xffffb78c0832a040)                 : 0xffffb78c0832a040 [Type: zvol_state *]
    [+0x000] zv_name          : "Z.d3c21a3e-354a-4431-abaf-55a9147349f7/e9126fea-9950-4686-a1b2-42aa420fc1e5" [Type: char [256]]
    [+0x100] zv_volsize       : 0x10000000000 [Type: unsigned __int64]
    [+0x108] zv_volblocksize  : 0x20000 [Type: unsigned __int64]
    [+0x110] zv_objset        : 0xffffb78c09095340 [Type: objset *]
    [+0x118] zv_flags         : 0x0 [Type: unsigned int]
    [+0x11c] zv_open_count    : 0x0 [Type: unsigned int]
    [+0x120] zv_changed       : 0x0 [Type: unsigned int]
    [+0x124] zv_volmode       : 0x0 [Type: unsigned int]
    [+0x128] zv_zilog         : 0x0 [Type: zilog *]
    [+0x130] zv_rangelock     [Type: zfs_rangelock]
    [+0x188] zv_dn            : 0x0 [Type: dnode *]
    [+0x190] zv_kstat         [Type: dataset_kstats]
    [+0x1c8] zv_next          [Type: list_node]
    [+0x1d8] zv_hash          : 0xad2ba41578fb3253 [Type: unsigned __int64]
    [+0x1e0] zv_hlink         [Type: hlist_node]
    [+0x1f0] zv_state_lock    [Type: kmutex]
    [+0x218] zv_suspend_ref   [Type: atomic_t]
    [+0x220] zv_suspend_lock  [Type: krwlock]
    [+0x298] zv_zso           : 0xffffb78c0a1a8068 [Type: zvol_state_os *]
27: kd> dt 0xffffb78c`0832a040
Symbol not found at address ffffb78c0832a040.
27: kd> !dt 0xffffb78c`0832a040
No export dt found
27: kd> .frame 0n12;dv /t /v
0c ffffc801`d6a42310 fffff809`d0bbdeb7 ZFSin!zil_replay+0xb8 [C:\test-build-branch\openzfs\module\zfs\zil.c @ 3629] 
<unavailable>     struct objset * os = <value unavailable>
@r14              void * arg = 0xffffb78c`0832a040
@rbx              <function> ** replay_func = 0xfffff809`d0d30ff0
ffffc801`d6a42340 struct zil_replay_arg zr = struct zil_replay_arg
@rsi              struct zilog * zilog = 0xffffb78c`193d9000
@rdi              struct zil_header * zh = 0xffffb78c`090955f0
27: kd> .frame 0n13;dv /t /v
0d ffffc801`d6a42390 fffff809`d0adc205 ZFSin!zvol_os_create_minor+0x217 [C:\test-build-branch\openzfs\module\os\windows\zfs\zvol_os.c @ 750] 
@rsi              char * name = 0xffffb78c`0ffe25a0 "Z.d3c21a3e-354a-4431-abaf-55a9147349f7/e9126fea-9950-4686-a1b2-42aa420fc1e5"
<unavailable>     int error = <value unavailable>
<unavailable>     unsigned int minor = <value unavailable>
@rdi              unsigned int64 hash = 0xad2ba415`78fb3253
@rbp              struct zvol_state * zv = 0xffffb78c`0832a040
<unavailable>     struct objset * os = <value unavailable>
@rbx              struct dmu_object_info * doi = 0xffffb78c`08b5e340
<unavailable>     unsigned int64 volsize = <value unavailable>
27: kd> dx -id 0,0,ffffbf8490a75800 -r1 ((ZFSin!zvol_state *)0xffffb78c0832a040)
((ZFSin!zvol_state *)0xffffb78c0832a040)                 : 0xffffb78c0832a040 [Type: zvol_state *]
    [+0x000] zv_name          : "Z.d3c21a3e-354a-4431-abaf-55a9147349f7/e9126fea-9950-4686-a1b2-42aa420fc1e5" [Type: char [256]]
    [+0x100] zv_volsize       : 0x10000000000 [Type: unsigned __int64]
    [+0x108] zv_volblocksize  : 0x20000 [Type: unsigned __int64]
    [+0x110] zv_objset        : 0xffffb78c09095340 [Type: objset *]
    [+0x118] zv_flags         : 0x0 [Type: unsigned int]
    [+0x11c] zv_open_count    : 0x0 [Type: unsigned int]
    [+0x120] zv_changed       : 0x0 [Type: unsigned int]
    [+0x124] zv_volmode       : 0x0 [Type: unsigned int]
    [+0x128] zv_zilog         : 0x0 [Type: zilog *]
    [+0x130] zv_rangelock     [Type: zfs_rangelock]
    [+0x188] zv_dn            : 0x0 [Type: dnode *]
    [+0x190] zv_kstat         [Type: dataset_kstats]
    [+0x1c8] zv_next          [Type: list_node]
    [+0x1d8] zv_hash          : 0xad2ba41578fb3253 [Type: unsigned __int64]
    [+0x1e0] zv_hlink         [Type: hlist_node]
    [+0x1f0] zv_state_lock    [Type: kmutex]
    [+0x218] zv_suspend_ref   [Type: atomic_t]
    [+0x220] zv_suspend_lock  [Type: krwlock]
    [+0x298] zv_zso           : 0xffffb78c0a1a8068 [Type: zvol_state_os *]

**Comment by lundman** [comment]
Something I had fixed in macOS version already, but someone missing bringing over.
aa2184b
