### ISSUE TITLE
taskq_thread() crash with prealloc'd tasks

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#62]
As commented in function taskq_thread(void *arg), if taskq_dispatch_ent() is used to enqueue, then the caller has the ownership of the tqe and it should not be accessed after tqe function returns. But here the caller has freed tqe and it is still accessed resulting in crash.

	/*
		 * For prealloc'd tasks, we don't free anything.  We
		 * have to check this now, because once we call the
		 * function for a prealloc'd taskq, we can't touch the
		 * tqent any longer (calling the function returns the
		 * ownershp of the tqent back to caller of
		 * taskq_dispatch.)
		 */

          tqe->tqent_func(tqe->tqent_arg);
            ....
	    /* If we were launched as canceled, do some book keeping */
		if (!(tq->tq_flags & TASKQ_DYNAMIC) && freeit &&
		    (tqe->tqent_un.tqent_flags & TQENT_FLAG_DELAYED)) {

![image](https://user-images.githubusercontent.com/84957265/143044296-157e9e73-0a5a-46b7-b52f-286f4f4e3ca7.png)

**Comment by lundman** [comment]
Ah how annoying - ok, will stuff the flags in a variable which should help. Thanks for the report.

**Comment by datacore-rm** [comment]
382a479b95046ff4ec7562791dc179062ee331d2
