### ISSUE TITLE
Failure while opening ZFS device object handle

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#64]
_C:\zfs>zpool status
wosix_open(\\.\ZFS): error -6 / 0xfffffffa
Failed to initialize the libzfs library._

**Issue:-**
zfsdev_state_init() does not set the FileObject minor value in the zs->zs_minor. Instead it sets some index number in it. Hence during close handle, the minor number is not found and not released from the zfsdev_state_list in zfsdev_release(). Once the open handle count reaches ZFSDEV_MAX_MINOR, all further open fails with ENXIO(6) error.

**Repro:-**
//Open and close the zfs device object handle ZFSDEV_MAX_MINOR times.
int main()
{
	#define	ZFSDEV_MAX_MINOR	(1 << 16) //65536
	HANDLE hDevice = INVALID_HANDLE_VALUE;
	
	for (int iter = 1; iter < (ZFSDEV_MAX_MINOR + 20); iter++)
	{
		hDevice = CreateFile(L"\\\\.\\ZFS", GENERIC_WRITE, FILE_SHARE_WRITE, 0, OPEN_EXISTING, 0, 0);
		
		if (hDevice == INVALID_HANDLE_VALUE)
		{
			printf("\nFailed to open ZFS device for iteration count = %d, error = %d\n", iter, GetLastError());
			return 1;
		}
		else
		{
			printf("%d\t", iter);
		}

		CloseHandle(hDevice);
	}

	return 0;
}

**Fix**?:-
@@ -7526,7 +7526,11 @@ zfsdev_state_init(void *priv)
+#if defined(_WIN32) && defined(_KERNEL)
+minor = minor((dev_t)priv);
+#else
        minor = zfsdev_minor_alloc();
+#endif
        if (minor == 0)
                return (SET_ERROR(ENXIO));

**Comment by lundman** [comment]
Ah yes, that makes sense - have you tested it already?

**Comment by datacore-rm** [comment]
Thanks. Yes, I have tested it. 

Also zfsdev_private_set_state() seems to corrupt the FILE_OBJECT struct. It is not required and can be defined as empty.

**Comment by datacore-rm** [comment]
b8a82d04acbc9667f0a19db8250d08f2f1556c8d
