### ISSUE TITLE
zdb.exe -d option  crashes

### ISSUE THREAD

**Issue by datacore-pnikhil** [openzfsonwindows/openzfs#73]
It's throwing an exception while debugging zdb.exe(Release) at line 3750 in zdb.c
<img width="626" alt="zdb -d issue 11" src="https://user-images.githubusercontent.com/81548655/154694940-2638a65a-9c83-4b25-81e7-aa67f519a615.png">

<img width="688" alt="zdb windbg exception" src="https://user-images.githubusercontent.com/81548655/154692587-c06e068e-820f-462a-a803-4964aac00a45.png">

->In above image, rax register should be referencing as pointer but it's referencing a variable

Debugging details:

![zdb -d issue 9 (2)](https://user-images.githubusercontent.com/81548655/154706454-fc0ac8bf-f41a-4fc9-ad3f-ebd21851e471.png)
![zdb -d issue 12 (3)](https://user-images.githubusercontent.com/81548655/154706478-a9fa1501-e401-4ff0-ad39-95a8c5e5a199.png)
![zdb -d issue 12 (5)](https://user-images.githubusercontent.com/81548655/154708328-0c05ba3f-8fba-4486-b452-d0c71ccbaadb.png)
![zdb -d issue 10](https://user-images.githubusercontent.com/81548655/154707047-7b98fc71-66e5-4362-81bf-4178e663670a.png)

-> The rax register register should be referencing to os_rootbp pointer, but it's referencing to os_primary_cache variable

**Comment by imtiazdc** [comment]
@lundman Is it because we are not including the correct headers leading to incorrect struct sizes?

**Comment by lundman** [comment]
zdb doesn't talk to kernel so it shouldn't be that userland and kernel have different structs, but it certainly looks to be a problem like that.
version looks quite wrong, perhaps memory was written to halfway through the struct?

**Comment by lundman** [comment]
with thanks
