### ISSUE TITLE
zpool doesn’t go into degraded state when a disk is unplugged

### ISSUE THREAD

**Issue by datacore-ramya** [openzfsonwindows/openzfs#85]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Windows Server 2019 Standard
Distribution Version	|1809
Kernel Version	|10.0.17763.1577
OpenZFS Version	|zfs-2.0.0-2,zfs-kmod-fixme

### Describe the problem you're observing
When a disk part of a raidz1 group is unplugged from VM using Hyper-V, zpool created doesn’t go into degraded state. 

### Describe how to reproduce the problem
1.	Create a raidz1 group with 3 disks
2.	Unplug 1 disk which is part of raidz1 group using Hyper-V remove disk. Run IO.
3.	Check zpool status. All disks and zpool state is Online.
4.	Reboot the machine and check zpool status. **On Reboot**, zpool state goes to degraded.

Expected behaviour: As per Linux OpenZFS environment, when a disk is unplugged, zpool immediately goes into degraded state.

**Comment by datacore-ramya** [comment]
Some observations I have found regarding this issue:
Behaviour in Linux:

When a disk is removed, a zio error is added which then calls for a probe on the vdev as shown below:
![image](https://user-images.githubusercontent.com/91878872/162165366-3e99c9e7-8958-41a1-a25e-fecff7bf1617.png)


_zio_vdev_io_done_ calls _vdev_probe_ when zio encounters an error. _vdev_probe_ attempts to reopen the vdev to check for errors. It adds a flag to call reopen on a separate thread.
![image](https://user-images.githubusercontent.com/91878872/162165408-923025f0-565e-4205-9a2b-02dd8d3ef58f.png)


In the above image, _spa_async_probe_ is called from _vdev_probe_. _vdev_reopen_ calls set state on a vdev.

ZFSin:

The behaviour is same as Linux except the thread is not created after _vdev_probe_ adds a flag to call _spa_async_probe_. 

Just before thread creation, there is a condition which always returns false.

vnode_t *rootdir = getrootdir(); → rootdir is always NULL. When this check(present in _spa_async_dispatch_) is commented, the state of pool is updated without reboot.

OpenZFS:

In this case, no zio error is registered. So _vdev_probe_ is not called.
Hope this gives some context for this issue.

**Comment by lundman** [comment]
OpenZFS: 
It's supposed to set the IOStatus here:
https://github.com/openzfsonwindows/openzfs/blob/windows/module/os/windows/zfs/vdev_disk.c#L788

then checked here:
https://github.com/openzfsonwindows/openzfs/blob/windows/module/os/windows/zfs/vdev_disk.c#L578

wonder why it doesn't survive the trip

**Comment by datacore-ramya** [comment]
https://github.com/openzfsonwindows/openzfs/blob/windows/module/os/windows/zfs/vdev_disk.c#L578
At this place, we are not able to get the status from "zio->windows.IoStatus.Status". Whereas the status is updated in this variable "zio->windows.irp->IoStatus.Status". "zio->windows.IoStatus" is an optional variable we pass on to "IoBuildAsynchronousFsdRequest" function. I guess irp's status is not copied to "zio->windows.IoStatus". Can we use  "zio->windows.irp->IoStatus.Status" itself? Or if there is a problem from our side with optional variable, any help with analyzing that?

**Comment by lundman** [comment]
I made `zio->windows.IoStatus` just to avoid another allocation (to get an iocompletion for the status code), which I thought was set with:
```
		irp = IoBuildAsynchronousFsdRequest(IRP_MJ_READ,
		    dvd->vd_DeviceObject,
		    zio->windows.b_addr,
		    (ULONG)zio->io_size,
		    &offset,
		    &zio->windows.IoStatus);
```
So, if that IoStatus just ignored? Perhaps we don't need to keep `zio->windows.IoStatus` at all then, if we can just grab it from `irp`. I'm a bit confused as to why the API requires it, but doesn't use it.

**Comment by datacore-ramya** [comment]
IRP structure has a member called "PIO_STATUS_BLOCK UserIosb" ([link](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_irp)). This variable has the same address as "zio->windows.IoStatus". This [link](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/how-completion-processing-is-performed) mentions:
The contents of Irp->IoStatus are copied to Irp->UserIosb so that the originator of the I/O request can see the final status of the operation.
as part of completion routine. Not sure why it is not copied.

**Comment by lundman** [comment]
Oh maybe it is only copied after we are completing the IRP. But yes for this problem, we should use irp.IoStatus.
