### ISSUE TITLE
Unable to destroy zvol.

### ISSUE THREAD

**Issue by datacore-skumar** [openzfsonwindows/openzfs#9]
zpool command : zpool create -o ashift=12 tank PHYSICALDRIVE1
zvol command : zfs create -o dedup=on -o compression=lz4 -o volblocksize=128k -o sync=always -V 45g tank/vol
![Screenshot (356)](https://user-images.githubusercontent.com/75466339/109611639-8bed8300-7b54-11eb-8b7a-f18688356611.png)

**Comment by lundman** [comment]
Hmm that is interesting - I wonder if I missed something, I'll go over the code again

**Comment by lundman** [comment]
Trickles down to dsl_destroy_head_check_impl(dsl_dataset_t *ds, int expected_holds)
```
	if (zfs_refcount_count(&ds->ds_longholds) != expected_holds)
		return (SET_ERROR(EBUSY));
```
where it expects holds to be 0, but is 1.   Under Unix it is only held during the open and close gap. In Windows, we keep it permanently "open", as long as it belongs to miniport. This will need some tweaking..

**Comment by lundman** [comment]
a00d883
35a9024
