### ISSUE TITLE
Bugcheck: BSD timer fires after driver Unload

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#92]
Issue: Bug check observed during driver uninstall. After driver unload routine returns, bsd timer which is still loaded, fires.

8: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD (d4)
A driver unloaded without cancelling lookaside lists, DPCs, worker threads, etc.
The broken driver's name is displayed on the screen and saved in
KiBugCheckDriver.
When possible, the guilty driver's name (Unicode string) is printed on
the bugcheck screen and saved in KiBugCheckDriver.
An attempt was made to access the driver at raised IRQL after it unloaded.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: fffff80c2d5898b0, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff800360f020d, address which referenced memory

Debugging Details:
------------------

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 2

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on HULK

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 2

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 75

    Key  : Analysis.System
    Value: CreateObject

BUGCHECK_CODE:  d4

BUGCHECK_P1: fffff80c2d5898b0

BUGCHECK_P2: 2

BUGCHECK_P3: 0

BUGCHECK_P4: fffff800360f020d

PROCESS_NAME:  System

STACK_TEXT:  
ffffd181`96874708 fffff800`361f3329 : 00000000`0000000a fffff80c`2d5898b0 00000000`00000002 00000000`00000000 : nt!KeBugCheckEx
ffffd181`96874710 fffff800`361f046c : 00000000`00000000 00000000`00000000 ffffd181`96840180 00000000`00000000 : nt!KiBugCheckDispatch+0x69
ffffd181`96874850 fffff800`360f020d : ffffd181`968469b0 00000000`001dcd64 00000000`00140001 00000000`00000000 : nt!KiPageFault+0x42c
ffffd181`968749e0 fffff800`361e693a : ffffffff`00000000 ffffd181`96840180 ffffd181`96850c00 ffff8205`af3ca040 : nt!KiRetireDpcList+0x3bd
ffffd181`96874c60 00000000`00000000 : ffffd181`96875000 ffffd181`9686f000 00000000`00000000 00000000`00000000 : nt!KiIdleLoop+0x5a

SYMBOL_NAME:  ZFSin.sys+2c98b0

MODULE_NAME: ZFSin

IMAGE_NAME:  ZFSin.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  2c98b0

FAILURE_BUCKET_ID:  0xD4_UNLOADED_MODULE_ZFSin.sys!unknown_function

OS_VERSION:  10.0.14393.4467

BUILDLAB_STR:  rs1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {c4001cde-4a4e-5b68-40f8-7d8c8a1cde69}

Followup:     MachineOwner
---------

**Comment by datacore-rm** [comment]
thanks

**Comment by lundman** [comment]
no, with my thanks! :)
